Repository kickstarter/ios-oss, pull requests merged in 2018-08, with the labels that each got.

#395 Adding Fabric & Crashlytics
  .gitignore
  Kickstarter-iOS/AppDelegate.swift
  Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift
  Kickstarter-iOS/ViewModels/AppDelegateViewModelTests.swift
  Kickstarter.xcodeproj/project.pbxproj
  Makefile
  Opentok.lock
  bin/fabric.sh
  circle.yml
Labels: ready to merge

#396 Discover card bug fix
  Kickstarter-iOS/Views/Controllers/CheckoutViewController.swift
  Kickstarter-iOS/Views/Controllers/ProjectPamphletContentViewController.swift
  Library/PKPaymentAuthorizationViewController.swift
  Library/ViewModels/RewardPledgeViewModel.swift
  Library/ViewModels/RewardPledgeViewModelTests.swift
Labels: ready to merge

#400 Upload dSYMs, add API key to plist, speed up enterprise builds
  .fastlane/Fastfile
  Kickstarter-iOS/AppDelegate.swift
  Kickstarter-iOS/Info.plist
  Library/AppEnvironment.swift
  Library/ViewModels/DiscoveryNavigationHeaderViewModel.swift
  Library/ViewModels/RewardCellViewModel.swift
Labels: needs review

#387 Facebook reconnect needed handling
  Kickstarter-iOS/DataSources/ActivitiesDataSourceTests.swift
  Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
  Kickstarter-iOS/Locales/de.lproj/Localizable.strings
  Kickstarter-iOS/Locales/es.lproj/Localizable.strings
  Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
  Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
  Kickstarter-iOS/Views/Cells/FindFriendsFacebookConnectCell.swift
  Kickstarter-iOS/Views/Controllers/ActivitiesViewControllerTests.swift
  Kickstarter-iOS/Views/Controllers/FindFriendsViewControllerTests.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/models/User.swift
  KsApi/models/lenses/UserLenses.swift
  KsApi/models/templates/UserTemplates.swift
  Library/FacebookConnectionType.swift
  Library/Strings.swift
  Library/ViewModels/ActivitiesViewModel.swift
  Library/ViewModels/ActivitiesViewModelTests.swift
  Library/ViewModels/FindFriendsFacebookConnectCellViewModel.swift
  Library/ViewModels/FindFriendsFaceookConnectCellViewModelTests.swift
  Library/ViewModels/FindFriendsViewModel.swift
  Library/ViewModels/FindFriendsViewModelTests.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.ActivitiesViewControllerTests/testMultipleSurveys_NeedsFacebookReconnect_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ActivitiesViewControllerTests/testMultipleSurveys_NeedsFacebookReconnect_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ActivitiesViewControllerTests/testMultipleSurveys_NeedsFacebookReconnect_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ActivitiesViewControllerTests/testMultipleSurveys_NeedsFacebookReconnect_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ActivitiesViewControllerTests/testMultipleSurveys_NeedsFacebookReconnect_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ActivitiesViewControllerTests/testMultipleSurveys_NotFacebookConnected_YouLaunched_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ActivitiesViewControllerTests/testMultipleSurveys_NotFacebookConnected_YouLaunched_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ActivitiesViewControllerTests/testMultipleSurveys_NotFacebookConnected_YouLaunched_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ActivitiesViewControllerTests/testMultipleSurveys_NotFacebookConnected_YouLaunched_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ActivitiesViewControllerTests/testMultipleSurveys_NotFacebookConnected_YouLaunched_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.FindFriendsViewControllerTests/testView_ShowFacebookReconnect_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.FindFriendsViewControllerTests/testView_ShowFacebookReconnect_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.FindFriendsViewControllerTests/testView_ShowFacebookReconnect_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.FindFriendsViewControllerTests/testView_ShowFacebookReconnect_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.FindFriendsViewControllerTests/testView_ShowFacebookReconnect_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.FindFriendsViewControllerTests/testView_ShowFacebookReconnect_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.FindFriendsViewControllerTests/testView_ShowFacebookReconnect_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.FindFriendsViewControllerTests/testView_ShowFacebookReconnect_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.FindFriendsViewControllerTests/testView_ShowFacebookReconnect_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.FindFriendsViewControllerTests/testView_ShowFacebookReconnect_lang_ja_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testCreator_lang_en@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testMember_lang_en@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testNonCreator_lang_en@2x.png
Labels: ready to merge

#404 Move & rename circle.yml to .circleci/config.yml
  .circleci/config.yml
Labels: enhancement

#401 Conditional creator digest notifications
  Kickstarter-iOS/DataSources/SettingsNotificationsDataSource.swift
  Kickstarter-iOS/DataSources/SettingsNotificationsDataSourceTests.swift
  Kickstarter-iOS/EmailFrequency.swift
  Kickstarter-iOS/Library/Nib.swift
  Kickstarter-iOS/SettingsNotificationCellType.swift
  Kickstarter-iOS/ViewModels/SettingsNotificationPickerViewModel.swift
  Kickstarter-iOS/ViewModels/SettingsNotificationPickerViewModelTests.swift
  Kickstarter-iOS/Views/Controllers/BetaToolsViewController.swift
  Kickstarter-iOS/Views/Controllers/SettingsNotificationsViewController.swift
  Kickstarter-iOS/Views/Controllers/SettingsNotificationsViewControllerTests.swift
  Kickstarter-iOS/Views/SettingsNotificationCell.swift
  Kickstarter-iOS/Views/SettingsNotificationPickerCell.swift
  Kickstarter-iOS/Views/Storyboards/SettingsNotificationPickerCell.xib
  Kickstarter-iOS/Views/Storyboards/SettingsNotifications.storyboard
  Kickstarter.xcodeproj/project.pbxproj
  Library/DataSource/ValueCellDataSource.swift
  Library/DataSource/ValueCellDataSourceTests.swift
  Library/ViewModels/SettingsNotificationsViewModel.swift
  Library/ViewModels/SettingsNotificationsViewModelTests.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.BetaToolsViewControllerTests/testBetaToolsViewController@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_isCreator_lang_ja_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsNotificationsViewControllerTests/testSettingsNotificationsViewController_lang_ja_device_phone5_8inch@2x.png
Labels: needs review

#408 Project notifications updates
  Kickstarter-iOS/Views/Cells/ProjectNotificationCell.swift
  Kickstarter-iOS/Views/Controllers/ProjectNotificationsViewController.swift
  Kickstarter-iOS/Views/Controllers/ProjectNotificationsViewControllerTests.swift
  Kickstarter-iOS/Views/Storyboards/Settings.storyboard
  Kickstarter-iOS/Views/Storyboards/SettingsV2.storyboard
  Kickstarter.xcodeproj/project.pbxproj
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ProjectNotificationsViewControllerTests/testProjectNotifications_lang_ja_device_phone5_8inch@2x.png
Labels: needs review

#409 Deleting unused CreatorDigestSettingsViewController
  Kickstarter-iOS/Views/Controllers/CreatorDigestSettingsViewController.swift
  Kickstarter-iOS/Views/Controllers/SettingsNotificationsViewController.swift
  Kickstarter-iOS/Views/Controllers/SettingsViewController.swift
  Kickstarter-iOS/Views/Storyboards/Settings.storyboard
  Kickstarter.xcodeproj/project.pbxproj
  Library/EmailFrequency.swift
  Library/SettingsCellType.swift
  Library/SettingsNotificationCellType.swift
  Library/ViewModels/CreatorDigestSettingsViewModel.swift
  Library/ViewModels/CreatorDigestSettingsViewModelTests.swift
Labels: needs review

#411 Backer Saved projects cell bug fix
  Kickstarter-iOS/Views/Controllers/BackerDashboardViewController.swift
Labels: ready to merge

#413 Added New Color for Settings
  Design/Colors.json
Labels: needs review

#417 Settings transition
  Kickstarter-iOS/Views/Controllers/BackerDashboardViewController.swift
  Kickstarter-iOS/Views/Controllers/SettingsViewController.swift
Labels: needs review
