Repository kickstarter/ios-oss, pull requests merged in 2018-05, with the labels that each got.

#350 Run swiftlint in build phase
  Kickstarter.xcodeproj/project.pbxproj
Labels: ready to merge

#353 Swiftlint record mode rule
  .swiftlint.yml
Labels: needs review

#355 Project category view bug fix for nil filter category
  Kickstarter-iOS/Views/Controllers/DiscoveryPageViewControllerTests.swift
  Library/ViewModels/DiscoveryPostcardViewModel.swift
  Library/ViewModels/DiscoveryPostcardViewModelTests.swift
Labels: needs review

#360 Gdpr following ui
  Kickstarter-iOS/Assets.xcassets/icons/icon--eye.imageset/Contents.json
  Kickstarter-iOS/Locales/de.lproj/Localizable.strings
  Kickstarter-iOS/Views/Controllers/SettingsViewController.swift
  Kickstarter-iOS/Views/Storyboards/Settings.storyboard
  KsApi/lib/Route.swift
  Library/Strings.swift
  Library/Styles/SettingsStyles.swift
  Library/UIAlertController.swift
  Library/ViewModels/SettingsViewModel.swift
  Library/ViewModels/SettingsViewModelTests.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.BackerDashboardProjectsViewControllerTests/testEmpty_BackedProjects_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.BackerDashboardProjectsViewControllerTests/testEmpty_BackedProjects_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.BackerDashboardProjectsViewControllerTests/testEmpty_BackedProjects_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.BackerDashboardProjectsViewControllerTests/testEmpty_BackedProjects_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.BackerDashboardProjectsViewControllerTests/testEmpty_BackedProjects_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.BackerDashboardProjectsViewControllerTests/testEmpty_BackedProjects_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.BackerDashboardProjectsViewControllerTests/testEmpty_BackedProjects_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.BackerDashboardProjectsViewControllerTests/testEmpty_BackedProjects_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.BackerDashboardProjectsViewControllerTests/testEmpty_BackedProjects_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.BackerDashboardProjectsViewControllerTests/testEmpty_BackedProjects_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.DashboardViewControllerTests/testView_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testCreator_lang_de@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testCreator_lang_en@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testCreator_lang_es@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testCreator_lang_fr@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testCreator_lang_ja@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testMember_lang_de@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testMember_lang_en@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testMember_lang_es@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testMember_lang_fr@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testMember_lang_ja@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testNonCreator_lang_de@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testNonCreator_lang_en@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testNonCreator_lang_es@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testNonCreator_lang_fr@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testNonCreator_lang_ja@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.SettingsViewControllerTests/testNonRelease@2x.png
Labels: GDPR, needs review
