Repository kickstarter/ios-oss, pull requests merged in 2018-10, with the labels that each got.

#442 Graph mutations clean
  Kickstarter-iOS/GraphError+LocalizedDescription.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphMutation.swift
  KsApi/GraphSchema.swift
  KsApi/MockService.swift
  KsApi/Service+RequestHelpers.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/ServiceTypeTests.swift
  KsApi/models/ChangePasswordInput.swift
  KsApi/mutations/Mutations.swift
  Library/AppEnvironment.swift
  Library/AppEnvironmentTests.swift
Labels: needs review

#443 Custom message banner
  Design/Colors.json
  Kickstarter-iOS/Assets.xcassets/icons/icon--alert.imageset/Contents.json
  Kickstarter-iOS/Assets.xcassets/icons/icon--alert.imageset/icon--alert.pdf
  Kickstarter-iOS/Assets.xcassets/icons/icon--confirmation.imageset/Contents.json
  Kickstarter-iOS/Assets.xcassets/icons/icon--confirmation.imageset/icon--confirmation.pdf
  Kickstarter-iOS/MessageBannerType.swift
  Kickstarter-iOS/ViewModels/MessageBannerViewModel.swift
  Kickstarter-iOS/ViewModels/MessageBannerViewModelTests.swift
  Kickstarter-iOS/Views/Controllers/ChangeEmailViewController.swift
  Kickstarter-iOS/Views/Controllers/MessageBannerViewController.swift
  Kickstarter-iOS/Views/Controllers/MessageBannerViewControllerTests.swift
  Kickstarter-iOS/Views/Storyboards/Settings.storyboard
  Kickstarter.xcodeproj/project.pbxproj
  Library/Styles/Colors.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerError_lang_ja_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerInfo_lang_ja_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_category_Art@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.MessageBannerViewControllerTests/testBannerSuccess_lang_ja_device_phone5_8inch@2x.png
Labels: ready to merge

#444 Change Password
  Kickstarter-iOS/Library/Nib.swift
  Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
  Kickstarter-iOS/Locales/de.lproj/Localizable.strings
  Kickstarter-iOS/Locales/es.lproj/Localizable.strings
  Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
  Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
  Kickstarter-iOS/TestHelpers/TraitController.swift
  Kickstarter-iOS/ViewModels/ChangePasswordViewModel.swift
  Kickstarter-iOS/ViewModels/ChangePasswordViewModelTests.swift
  Kickstarter-iOS/ViewModels/LoadingBarButtonItemViewModel.swift
  Kickstarter-iOS/ViewModels/LoadingBarButtonItemViewModelTests.swift
  Kickstarter-iOS/Views/Controllers/ChangePasswordViewController.swift
  Kickstarter-iOS/Views/Controllers/ChangePasswordViewControllerTests.swift
  Kickstarter-iOS/Views/LoadingBarButtonItemView.swift
  Kickstarter-iOS/Views/Storyboards/LoadingBarButtonItemView.xib
  Kickstarter-iOS/Views/Storyboards/Settings.storyboard
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/MockService.swift
  Library/Strings.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_de_device_phone4inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_de_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_en_device_phone4inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_en_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_es_device_phone4inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_es_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_fr_device_phone4inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_fr_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_ja_device_phone4inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_ja_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ChangePasswordViewControllerTests/testChangePassword_lang_ja_device_phone5_8inch@2x.png
Labels: ready to merge

#448 Fetch user currency query
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphSchema.swift
  KsApi/GraphSchemaTests.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/models/UserCurrency.swift
  KsApi/models/UserEnvelope.swift
  KsApi/queries/UserQueries.swift
  KsApi/queries/UserQueriesTests.swift
Labels: ready to merge

#445 Emoji logging ✨
  KsApi/Service+RequestHelpers.swift
  KsApi/extensions/NSURLSession.swift
  Library/Koala/KoalaTrackingClient.swift
Labels: enhancement, ready to merge

#455 Fix provisioning regression
  Gemfile.lock
  Kickstarter.xcodeproj/project.pbxproj
Labels: needs review

#461 Log custom events to Crashlytics
  Kickstarter.xcodeproj/project.pbxproj
  Library/Koala/KoalaTrackingClient.swift
Labels: ready to merge

#464 Updating Change Password logout animation
  Kickstarter-iOS/ViewModels/ChangePasswordViewModel.swift
  Kickstarter-iOS/ViewModels/ChangePasswordViewModelTests.swift
  Kickstarter-iOS/Views/Controllers/ChangePasswordViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/mutations/inputs/ChangeCurrencyInput.swift
  KsApi/mutations/inputs/ChangeEmailInput.swift
  KsApi/mutations/inputs/ChangePasswordInput.swift
Labels: needs review
