Repository kickstarter/ios-oss, pull requests merged in 2021-07, with the labels that each got.

#1537 [NT-2042] UI – Handle URLs in comments
  Kickstarter-iOS/Views/Controllers/CommentsViewControllerTests.swift
  Library/Styles/CommentCellStyles.swift
Labels: ready to merge

#1539 [NT-2090] Refactor Replies DataSource
  Kickstarter-iOS/DataSources/CommentRepliesDataSource.swift
  Kickstarter-iOS/DataSources/CommentRepliesDataSourceTests.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewController.swift
  Library/DataSource/ValueCellDataSource.swift
  Library/DataSource/ValueCellDataSourceTests.swift
Labels: needs review

#1540 [NT-1944] UI - User badges
  Kickstarter-iOS/Views/CommentCellHeaderStackView.swift
  Kickstarter-iOS/Views/CommentCellHeaderStackViewTests.swift
  KsApi/models/Comment.swift
  KsApi/models/templates/CommentTemplates.swift
  Library/Styles/CommentCellStyles.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentCellHeaderStackViewTests/testAuthorBadge_Collaborator_state_AuthorBadge_Is_Colaborator@2x.png
Labels: needs review

#1538 [NT-1917, NT-2062] Apollo GraphQL Client Implementation
  .circleci/config.yml
  .slather.yml
  .swiftformat
  Cartfile
  Cartfile.resolved
  Carthage-xcfilelist/app-input-files.xcfilelist
  Carthage-xcfilelist/app-output-files.xcfilelist
  Carthage-xcfilelist/ksapi-input-files.xcfilelist
  Carthage-xcfilelist/ksapi-output-files.xcfilelist
  Kickstarter-iOS/Views/Controllers/CommentsViewControllerTests.swift
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-Framework-iOS.xcscheme
  Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-iOS.xcscheme
  Kickstarter.xcodeproj/xcshareddata/xcschemes/KickstarterUITests.xcscheme
  Kickstarter.xcodeproj/xcshareddata/xcschemes/KsApi.xcscheme
  Kickstarter.xcodeproj/xcshareddata/xcschemes/Library-iOS.xcscheme
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/extensions/ApolloClient+RAC.swift
  KsApi/extensions/ApolloClient+Singleton.swift
  KsApi/extensions/ApolloInterceptors.swift
  KsApi/extensions/ApolloInterceptorsTests.swift
  KsApi/fragments/CommentFragment.graphql
  KsApi/graphql-schema.json
  KsApi/models/CommentsEnvelope.swift
  KsApi/models/graphql/GraphCommentsEnvelope.swift
  KsApi/models/graphql/GraphCommentsEnvelopeTests.swift
  KsApi/models/graphql/adapters/Comment+GraphComment.swift
  KsApi/models/graphql/adapters/CommentsEnvelope+GraphCommentsEnvelope.swift
  KsApi/models/graphql/adapters/CommentsEnvelope+GraphCommentsEnvelopeTests.swift
  KsApi/models/templates/graphql/GraphCommentsEnvelopeTemplates.swift
  KsApi/queries/CommentsQueries.swift
  KsApi/queries/CommentsQueriesTests.swift
  KsApi/queries/FetchProjectComments.graphql
  KsApi/queries/FetchUpdateComments.graphql
  Library/ViewModels/CommentsViewModel.swift
  Library/ViewModels/CommentsViewModelTests.swift
Labels: needs review

#1543 [NT-1941] Post A Reply
  Kickstarter-iOS/DataSources/CommentRepliesDataSource.swift
  Kickstarter-iOS/DataSources/CommentRepliesDataSourceTests.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewController.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewControllerTests.swift
  KsApi/models/Comment.swift
  KsApi/models/CommentTests.swift
  KsApi/models/templates/CommentRepliesEnvelopeTemplates.swift
  KsApi/models/templates/CommentTemplates.swift
  KsApi/mutations/PostCommentMutation.swift
  KsApi/mutations/PostCommentMutationTests.swift
  Library/ViewModels/CommentRepliesViewModel.swift
  Library/ViewModels/CommentRepliesViewModelTests.swift
  Library/ViewModels/CommentsViewModel.swift
  Library/ViewModels/CommentsViewModelTests.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_ja_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootComment_Comments___lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootComment_Comments___lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootComment_Comments___lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootComment_Comments___lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootComment_Comments___lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootComment_Comments___lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootComment_Comments___lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootComment_Comments___lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootComment_Comments___lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootComment_Comments___lang_ja_device_phone5_8inch@2x.png
Labels: needs review

#1544 [NT-2054] Add pagination to comment replies
  Kickstarter-iOS/DataSources/CommentRepliesDataSource.swift
  Kickstarter-iOS/DataSources/CommentRepliesDataSourceTests.swift
  Kickstarter-iOS/Views/Cells/CommentCell.swift
  Kickstarter-iOS/Views/Cells/ViewMoreRepliesCell.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/models/templates/CommentRepliesEnvelopeTemplates.swift
  Library/Styles/CommentCellStyles.swift
  Library/ViewModels/CommentRepliesViewModel.swift
  Library/ViewModels/CommentRepliesViewModelTests.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndReplies_Comments___lang_ja_device_phone5_8inch@2x.png
Labels: needs review

#1546 [NT-2072] Backing From BackingFragment
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/models/graphql/adapters/Backing+BackingFragment.swift
  KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
  KsApi/models/graphql/adapters/Comment+CommentFragment.swift
  KsApi/models/graphql/adapters/Comment+GraphComment.swift
  KsApi/models/graphql/adapters/User+UserFragment.swift
Labels: needs review

#1549 [NT-1995] Handle pagination failure on comment reply threads
  Kickstarter-iOS/DataSources/CommentRepliesDataSource.swift
  Kickstarter-iOS/DataSources/CommentRepliesDataSourceTests.swift
  Kickstarter-iOS/Views/Cells/CommentViewMoreRepliesFailedCell.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewController.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewControllerTests.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/ViewModels/CommentRepliesViewModel.swift
  Library/ViewModels/CommentRepliesViewModelTests.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailingReplies_CommentReplies___lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailingReplies_CommentReplies___lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailingReplies_CommentReplies___lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailingReplies_CommentReplies___lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailingReplies_CommentReplies___lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailingReplies_CommentReplies___lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailingReplies_CommentReplies___lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailingReplies_CommentReplies___lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailingReplies_CommentReplies___lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailingReplies_CommentReplies___lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentNoReplies_CommentReplies___lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentNoReplies_CommentReplies___lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentNoReplies_CommentReplies___lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentNoReplies_CommentReplies___lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentNoReplies_CommentReplies___lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentNoReplies_CommentReplies___lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentNoReplies_CommentReplies___lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentNoReplies_CommentReplies___lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentNoReplies_CommentReplies___lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentNoReplies_CommentReplies___lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentRepliesandViewMoreRepliesFailedCell_CommentReplies___lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentRepliesandViewMoreRepliesFailedCell_CommentReplies___lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentRepliesandViewMoreRepliesFailedCell_CommentReplies___lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentRepliesandViewMoreRepliesFailedCell_CommentReplies___lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentRepliesandViewMoreRepliesFailedCell_CommentReplies___lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentRepliesandViewMoreRepliesFailedCell_CommentReplies___lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentRepliesandViewMoreRepliesFailedCell_CommentReplies___lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentRepliesandViewMoreRepliesFailedCell_CommentReplies___lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentRepliesandViewMoreRepliesFailedCell_CommentReplies___lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentRepliesandViewMoreRepliesFailedCell_CommentReplies___lang_ja_device_phone4_7inch@2x.png
Labels: needs review

#1548 [NT-1998] Retry Failed Reply
  Kickstarter-iOS/DataSources/CommentRepliesDataSource.swift
  Kickstarter-iOS/DataSources/CommentRepliesDataSourceTests.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewController.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewControllerTests.swift
  KsApi/models/templates/CommentRepliesEnvelopeTemplates.swift
  KsApi/models/templates/CommentsEnvelopeTemplates.swift
  Library/ViewModels/CommentRepliesViewModel.swift
  Library/ViewModels/CommentRepliesViewModelTests.swift
  Library/ViewModels/CommentsViewModel.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessFailedRetryingRetrySuccessComments_ShouldDisplayAll_CommentReplies___lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessFailedRetryingRetrySuccessComments_ShouldDisplayAll_CommentReplies___lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessFailedRetryingRetrySuccessComments_ShouldDisplayAll_CommentReplies___lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessFailedRetryingRetrySuccessComments_ShouldDisplayAll_CommentReplies___lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessFailedRetryingRetrySuccessComments_ShouldDisplayAll_CommentReplies___lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessFailedRetryingRetrySuccessComments_ShouldDisplayAll_CommentReplies___lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessFailedRetryingRetrySuccessComments_ShouldDisplayAll_CommentReplies___lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessFailedRetryingRetrySuccessComments_ShouldDisplayAll_CommentReplies___lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessFailedRetryingRetrySuccessComments_ShouldDisplayAll_CommentReplies___lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessFailedRetryingRetrySuccessComments_ShouldDisplayAll_CommentReplies___lang_ja_device_phone4_7inch@2x.png
Labels: needs review

#1550 [NT-2072] Update Manage Pledge View To Use Apollo Query
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/fragments/ProjectFragment.graphql
  KsApi/fragments/RewardFragment.graphql
  KsApi/models/ProjectAndBackingEnvelope.swift
  KsApi/models/graphql/adapters/Backing+BackingFragment.swift
  KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
  KsApi/models/graphql/adapters/Project+ProjectFragment.swift
  KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
  KsApi/models/graphql/adapters/Project.Category+CategoryFragment.swift
  KsApi/models/graphql/adapters/Project.Category+CategoryFragmentTests.swift
  KsApi/models/graphql/adapters/Project.Country+CountryFragment.swift
  KsApi/models/graphql/adapters/Project.Country+CountryFragmentTests.swift
  KsApi/models/graphql/adapters/Reward+RewardFragment.swift
  KsApi/models/graphql/adapters/Reward+RewardFragmentTests.swift
  KsApi/models/graphql/adapters/User+UserFragment.swift
  KsApi/models/graphql/adapters/User+UserFragmentTests.swift
  Library/ViewModels/ManagePledgeViewModel.swift
Labels: needs review

#1551 [NT-2073] Migrate Reward Add-On Selection Query To Apollo
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/fragments/RewardFragment.graphql
  KsApi/fragments/ShippingRuleFragment.graphql
  KsApi/models/graphql/adapters/Project+FetchAddOnsQueryData.swift
  KsApi/models/graphql/adapters/Project+FetchAddOnsQueryDataTests.swift
  KsApi/models/graphql/adapters/Reward+RewardFragment.swift
  KsApi/models/graphql/adapters/Reward+RewardFragmentTests.swift
  KsApi/models/graphql/adapters/ShippingRule+ShippingRuleFragment.swift
  KsApi/models/graphql/adapters/ShippingRule+ShippingRuleFragmentTests.swift
  KsApi/queries/FetchAddOnsQuery.graphql
  Library/ViewModels/RewardAddOnSelectionViewModel.swift
Labels: needs review

#1553 [NT-2073] Don't Fetch Expanded Shipping Rules For Digital-Only Rewards
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/queries/FetchAddOnsQuery.graphql
  Library/ViewModels/RewardAddOnSelectionViewModel.swift
Labels: needs review

#1554 [NT-1994] Handling error when requesting first page of replies.
  Kickstarter-iOS/DataSources/CommentRepliesDataSource.swift
  Kickstarter-iOS/DataSources/CommentRepliesDataSourceTests.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewController.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewControllerTests.swift
  KsApi/models/templates/CommentRepliesEnvelopeTemplates.swift
  Library/ViewModels/CommentRepliesViewModel.swift
  Library/ViewModels/CommentRepliesViewModelTests.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailureToRequestFirstPage_CommentReplies___lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailureToRequestFirstPage_CommentReplies___lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailureToRequestFirstPage_CommentReplies___lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailureToRequestFirstPage_CommentReplies___lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailureToRequestFirstPage_CommentReplies___lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailureToRequestFirstPage_CommentReplies___lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailureToRequestFirstPage_CommentReplies___lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailureToRequestFirstPage_CommentReplies___lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailureToRequestFirstPage_CommentReplies___lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndFailureToRequestFirstPage_CommentReplies___lang_ja_device_phone4_7inch@2x.png
Labels: needs review

#1557 [NT-2131] Adding translated strings for native comment threading work
  Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
  Kickstarter-iOS/Locales/de.lproj/Localizable.strings
  Kickstarter-iOS/Locales/es.lproj/Localizable.strings
  Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
  Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
  Kickstarter-iOS/Views/Cells/ViewMoreRepliesCell.swift
  Kickstarter-iOS/Views/CommentCellHeaderStackView.swift
  Kickstarter-iOS/Views/Controllers/CommentRepliesViewController.swift
  Library/Strings.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.CommentRepliesViewControllerTests/testViewController_WithRootCommentAndSuccessfulReplies_CommentReplies___lang_ja_device_phone4_7inch@2x.png
Labels: needs review

#1555 [NT-2104] Migrate CreateBacking To Apollo
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/extensions/ApolloClient+RAC.swift
  KsApi/fragments/CheckoutFragment.graphql
  KsApi/models/ErrorEnvelope.swift
  KsApi/models/graphql/adapters/Checkout+CheckoutFragment.swift
  KsApi/models/graphql/adapters/CreateBackingEnvelope+CreateBackingMutation.Data.swift
  KsApi/models/graphql/adapters/CreateBackingEnvelope+CreateBackingMutation.DataTests.swift
  KsApi/models/graphql/adapters/GraphAPI.ApplePay+ApplePayParams.swift
  KsApi/models/graphql/adapters/GraphAPI.CreateBackingInput+CreateBackingInput.swift
  KsApi/models/graphql/adapters/GraphAPI.CreateBackingInput+CreateBackingInputTests.swift
  KsApi/models/graphql/adapters/GraphAPI.UpdateBackingInput+UpdateBackingInput.swift
  KsApi/models/graphql/adapters/GraphAPI.UpdateBackingInput+UpdateBackingInputTests.swift
  KsApi/models/graphql/adapters/UpdateBackingEnvelope+UpdateBackingMutation.Data.swift
  KsApi/models/graphql/adapters/UpdateBackingEnvelope+UpdateBackingMutation.DataTests.swift
  KsApi/mutations/CreateBacking.graphql
  KsApi/mutations/UpdateBacking.graphql
  Library/ErrorEnvelope+LocalizedDescription.swift
  Library/ViewModels/LoginToutViewModelTests.swift
  Library/ViewModels/PledgeViewModel.swift
  Library/ViewModels/PledgeViewModelTests.swift
Labels: blocked

#1558 [NT-1985] Deprecate iOS 12
  Kickstarter-iOS/Views/Controllers/CategorySelectionViewController.swift
  Kickstarter-iOS/Views/Controllers/DashboardViewController.swift
  Kickstarter-iOS/Views/LoadingButton.swift
  Kickstarter-iOS/Views/ProcessingView.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/NavigationController.swift
  Library/Styles/BaseStyles.swift
  Library/UIScrollView+Extensions.swift
Labels: needs review

#1559 [NT-2074] Download GraphQL Schema During CI Builds
  .circleci/config.yml
  bin/apollo-schema-download.sh
Labels: needs review

#1560 [NT-2137] Upload dSYMs During App Store Delivery
  .fastlane/Fastfile
Labels: needs review

#1561 [NT-2114] Adding collaboratorPermissions to ProjectFragment
  KsApi/GraphAPI.swift
  KsApi/fragments/ProjectFragment.graphql
  KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
  KsApi/models/graphql/adapters/Project+FetchAddOnsQueryDataTests.swift
  KsApi/models/graphql/adapters/Project+ProjectFragment.swift
  KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
Labels: needs review

#1562 [NT-2040] Enable Segment By Default
  Library/Tracking/Segment.swift
Labels: needs review

#1563 [NT-2115] Add Personalization To Project Fragment
  KsApi/GraphAPI.swift
  KsApi/fragments/ProjectFragment.graphql
  KsApi/models/ProjectAndBackingEnvelope.swift
  KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
  KsApi/models/graphql/adapters/Project+FetchAddOnsQueryDataTests.swift
  KsApi/models/graphql/adapters/Project+ProjectFragment.swift
  KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
Labels: needs review

#1565 [NT-2110] Update User Account Mutation
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/models/UpdateAcccountEnvelope.swift
  KsApi/models/graphql/adapters/Comment+CommentFragmentTests.swift
  KsApi/models/graphql/adapters/GraphAPI.UpdateUserAccountInput+UpdateUserAccountInput.swift
  KsApi/models/graphql/adapters/GraphAPI.UpdateUserAccountInput+UpdateUserAccountInputTests.swift
  KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
  KsApi/models/graphql/adapters/UpdateAccountEnvelope+UpdateAccountEnvelope.Data.swift
  KsApi/models/graphql/adapters/UpdateAccountEnvelope+UpdateAccountEnvelope.DataTests.swift
  KsApi/models/graphql/adapters/UpdateBackingEnvelope+UpdateBackingMutation.Data.swift
  KsApi/mutations/UpdateUserAccount.graphql
  Library/ViewModels/ChangeEmailViewModelTests.swift
  Library/ViewModels/ChangePasswordViewModelTests.swift
  Library/ViewModels/CreatePasswordViewModelTests.swift
Labels: needs review

#1566 [NT-2113] Migrate WatchProjectMutation to Apollo
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/models/graphql/WatchProjectResponseEnvelope.swift
  KsApi/models/graphql/adapters/GraphAPI.WatchProjectInput+WatchProjectInput.swift
  KsApi/models/graphql/adapters/GraphAPI.WatchProjectInput+WatchProjectInputTests.swift
  KsApi/models/graphql/adapters/WatchProjectResponseEnvelope+WatchProjectMutation.Data.swift
  KsApi/models/graphql/adapters/WatchProjectResponseEnvelope+WatchProjectMutation.DataTests.swift
  KsApi/models/templates/graphql/WatchProjectResponseEnvelopeTemplates.swift
  KsApi/mutations/WatchProject.graphql
  KsApi/mutations/inputs/WatchProjectInput.swift
  KsApi/mutations/inputs/WatchProjectInputTests.swift
  Library/ViewModels/WatchProjectViewModel.swift
  Library/ViewModels/WatchProjectViewModelTests.swift
Labels: needs review

#1569 [NT-2101] Migrating CancelBacking mutation to Apollo.
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/GraphMutation.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/mutations/CancelBacking.graphql
  Library/ViewModels/CancelPledgeViewModelTests.swift
Labels: needs review

#1568 [NT-2111] Update User Profile Mutation
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/models/UpdateAcccountEnvelope.swift
  KsApi/models/graphql/adapters/Comment+CommentFragment.swift
  KsApi/models/graphql/adapters/GraphAPI.UpdateUserProfileInput+UpdateUserProfileInput.swift
  KsApi/models/graphql/adapters/GraphAPI.UpdateUserProfileInput+UpdateUserProfileInputTests.swift
  KsApi/models/graphql/adapters/UpdateAccountEnvelope+UpdateAccountEnvelope.Data.swift
  KsApi/models/graphql/adapters/UpdateAccountEnvelope+UpdateAccountEnvelope.DataTests.swift
  KsApi/mutations/UpdateUserProfile.graphql
  Library/ViewModels/ChangeEmailViewModelTests.swift
  Library/ViewModels/ChangePasswordViewModelTests.swift
  Library/ViewModels/CreatePasswordViewModelTests.swift
  Library/ViewModels/SelectCurrencyViewModelTests.swift
Labels: needs review

#1570 Handling target = blank for webview URL navigation in WKUIDelegate.
  Kickstarter-iOS/Library/WebViewController.swift
Labels: needs review

#1572 [NT-2120] Migrating query for fetching user backings to Apollo.
  Kickstarter-iOS/Views/Controllers/ActivitiesViewControllerTests.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/models/BackingsEnvelope.swift
  KsApi/models/ErroredBackingsEnvelope.swift
  KsApi/models/ErroredBackingsEnvelopeTests.swift
  KsApi/models/graphql/adapters/GraphAPI.BackingState+BackingState.swift
  KsApi/models/graphql/adapters/GraphAPI.BackingState+BackingStateTests.swift
  KsApi/queries/FetchUserBackings.graphql
  Library/ViewModels/ActivitiesViewModel.swift
  Library/ViewModels/ActivitiesViewModelTests.swift
Labels: needs review

#1571 [NT-2105] Mutation Create Payment Source
  Kickstarter-iOS/DataSources/PaymentMethodsDataSource.swift
  Kickstarter-iOS/DataSources/PaymentMethodsDataSourceTests.swift
  Kickstarter-iOS/DataSources/PledgePaymentMethodsDataSourceTests.swift
  Kickstarter-iOS/Views/Cells/CreditCardCell.swift
  Kickstarter-iOS/Views/Cells/PledgePaymentMethodCell.swift
  Kickstarter-iOS/Views/Controllers/AddNewCardViewController.swift
  Kickstarter-iOS/Views/Controllers/PaymentMethodsViewController.swift
  Kickstarter-iOS/Views/Controllers/PledgePaymentMethodsViewController.swift
  Kickstarter-iOS/Views/Controllers/PledgeViewControllerTests.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/models/CreatePaymentSourceEnvelope.swift
  KsApi/models/DeletePaymentMethodEnvelope.swift
  KsApi/models/graphql/GraphUser.swift
  KsApi/models/graphql/UserCreditCards.swift
  KsApi/models/graphql/UserCreditCardsTests.swift
  KsApi/models/graphql/adapters/CreatePaymentSourceEnvelope+CreatePaymentSourceMutation.Data.swift
  KsApi/models/graphql/adapters/CreatePaymentSourceEnvelope+CreatePaymentSourceMutation.DataTests.swift
  KsApi/models/graphql/adapters/GraphAPI.CreatePaymentSourceInput+CreatePaymentSourceInput.swift
  KsApi/models/graphql/adapters/GraphAPI.CreatePaymentSourceInput+CreatePaymentSourceInputTests.swift
  KsApi/models/graphql/adapters/GraphUserCreditCard+UserFragment.swift
  KsApi/models/graphql/adapters/UserCreditCards+UserFragment.swift
  KsApi/models/graphql/adapters/UserCreditCards+UserFragmentTests.swift
  KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelope.swift
  KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelopeTests.swift
  KsApi/models/templates/CreatePaymentSourceTemplate.swift
  KsApi/models/templates/graphql/GraphCreditCardTemplate.swift
  KsApi/models/templates/graphql/GraphUserTemplates.swift
  KsApi/mutations/CreatePaymentSource.graphql
  Library/CreateBackingConstructorTests.swift
  Library/CreditCard+Utils.swift
  Library/CreditCard+UtilsTests.swift
  Library/UpdateBackingInput+ConstructorTests.swift
  Library/ViewModels/AddNewCardViewModel.swift
  Library/ViewModels/AddNewCardViewModelTests.swift
  Library/ViewModels/CreditCardCellViewModel.swift
  Library/ViewModels/CreditCardCellViewModelTests.swift
  Library/ViewModels/PaymentMethodsViewModel.swift
  Library/ViewModels/PaymentMethodsViewModelTests.swift
  Library/ViewModels/PledgePaymentMethodCellViewModel.swift
  Library/ViewModels/PledgePaymentMethodCellViewModelTests.swift
  Library/ViewModels/PledgePaymentMethodsViewModel.swift
  Library/ViewModels/PledgePaymentMethodsViewModelTests.swift
Labels: needs review
