Repository kickstarter/ios-oss, pull requests merged in 2022-09, with the labels that each got.

#1718 [Unticketed] Updated Stripe Framework
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: needs review

#1717 [NTV-605] Alamofire/AlamofireImage Carthage -> SPM
  Cartfile
  Cartfile.resolved
  Carthage-xcfilelist/app-input-files.xcfilelist
  Carthage-xcfilelist/app-output-files.xcfilelist
  Carthage-xcfilelist/kickstarter-framework-input-files.xcfilelist
  Carthage-xcfilelist/kickstarter-framework-output-files.xcfilelist
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: WIP, needs review

#1722 [NTV-606] KingFisher Carthage -> SPM
  Cartfile
  Cartfile.resolved
  Carthage-xcfilelist/app-input-files.xcfilelist
  Carthage-xcfilelist/app-output-files.xcfilelist
  Carthage-xcfilelist/kickstarter-framework-input-files.xcfilelist
  Carthage-xcfilelist/kickstarter-framework-output-files.xcfilelist
  Carthage-xcfilelist/library-input-files.xcfilelist
  Carthage-xcfilelist/library-output-files.xcfilelist
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: needs review

#1723 [NTV-609] Migrates SwiftSoup to SPM
  Cartfile
  Cartfile.resolved
  Carthage-xcfilelist/app-input-files.xcfilelist
  Carthage-xcfilelist/ksapi-input-files.xcfilelist
  Carthage-xcfilelist/ksapi-output-files.xcfilelist
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: needs review

#1729 [NTV-614] Firebase Binaries To SPM
  Cartfile
  Cartfile.resolved
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: needs review

#1728 [NTV-616] Moves FBSnapshotTestCase to iOSSnapshotTestCase Swift Package
  Cartfile
  Cartfile.resolved
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Library/TestHelpers/TestCase.swift
Labels: ready to merge

#1731 [NTV-1896] Present Payment Sheet With Feature Flag Enabled.
  Kickstarter-iOS/Features/PaymentMethods/Controller/PaymentMethodsViewController.swift
  KsApi/GraphAPI.swift
  KsApi/graphql-schema.json
  KsApi/mutations/inputs/CreateSetupIntentInput.swift
  KsApi/mutations/inputs/CreateSetupIntentInputTests.swift
  Library/ViewModels/PaymentMethodsViewModel.swift
  Library/ViewModels/PaymentMethodsViewModelTests.swift
Labels: needs review

#1730 [WEB-739] Migrates AppCenterDistribute to SPM
  Cartfile
  Cartfile.resolved
  Kickstarter-iOS/AppDelegate.swift
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: needs review

#1733 [PAY-1900] [PAY-1898] Create Payment Source From Payment Sheet
  Kickstarter-iOS/Features/PaymentMethods/Controller/PaymentMethodsViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/models/graphql/adapters/GraphAPI.CreatePaymentSourceInput+CreatePaymentSourceInput.swift
  KsApi/models/graphql/adapters/GraphAPI.CreatePaymentSourceInput+CreatePaymentSourceInputTests.swift
  KsApi/models/templates/CreatePaymentSourceTemplate.swift
  KsApi/mutations/inputs/CreatePaymentSourceSetupIntentInput.swift
  KsApi/mutations/inputs/CreatePaymentSourceSetupIntentInputTests.swift
  Library/CreatePaymentSourceSetupIntentClientSecret+Constructor.swift
  Library/CreatePaymentSourceSetupIntentClientSecret+ConstructorTests.swift
  Library/TestHelpers/Stripe+PaymentMethod.swift
  Library/ViewModels/PaymentMethodsViewModel.swift
  Library/ViewModels/PaymentMethodsViewModelTests.swift
  Library/ViewModels/PledgePaymentMethodsViewModelTests.swift
Labels: needs review

#1734 [WEB-742] Migrates PerimeterX to SPM
  Cartfile
  Cartfile.resolved
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: needs review

#1738 [PAY-1954] Loading User Settings And Cancelling Payment Sheet
  Kickstarter-iOS/Features/PaymentMethods/Controller/PaymentMethodsViewController.swift
  Kickstarter-iOS/Features/PaymentMethods/Storyboard/PaymentMethodsFooterView.xib
  Kickstarter-iOS/Features/PaymentMethods/Views/PaymentMethodsFooterView.swift
  Library/ViewModels/PaymentMethodsViewModel.swift
  Library/ViewModels/PaymentMethodsViewModelTests.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_de_device_phone4inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_de_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_en_device_phone4inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_en_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_es_device_phone4inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_es_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_fr_device_phone4inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_fr_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_ja_device_phone4inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_ja_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_NoCreditCards_lang_ja_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_de_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_en_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_es_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_fr_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_ja_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_ja_device_phone5_5inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.PaymentMethodsViewControllerTests/testView_WithCreditCards_lang_ja_device_phone5_8inch@2x.png
Labels: needs review

#1740 [Unticketed] PerimeterX Beta Build 5.4.0 (16642229) Crash
  Kickstarter.xcodeproj/project.pbxproj
Labels: needs review

#1739 [Unticketed] Release 5.5.0 to Main
  Kickstarter.xcodeproj/project.pbxproj
Labels: needs review
