Repository kickstarter/ios-oss, pull requests merged in 2023-01, with the labels that each got.

#1767 CircleCI fixes
  .circleci/config.yml
  .fastlane/beta-changelog.rb
  .fastlane/beta-post-s3.rb
  Gemfile
  Gemfile.lock
  ops/cfn/0-ci.yml
Labels: enhancement

#1764 [WEB-861] Consent Management feature flag
  Kickstarter-iOS/Features/OptimizelyFeatureFlagTools/Controller/OptimizelyFeatureFlagToolsViewControllerTests.swift
  Library/OptimizelyClientTypeTests.swift
  Library/OptimizelyFeature+Helpers.swift
  Library/OptimizelyFeature+HelpersTests.swift
  Library/OptimizelyFeature.swift
  Library/ViewModels/OptimizelyFeatureFlagToolsViewModel.swift
  Library/ViewModels/OptimizelyFeatureFlagToolsViewModelTests.swift
Labels: ready to merge

#1766 [WEB-669] Facebook Conversions API Feature Flag
  Library/OptimizelyClientTypeTests.swift
  Library/OptimizelyFeature+Helpers.swift
  Library/OptimizelyFeature+HelpersTests.swift
  Library/OptimizelyFeature.swift
  Library/ViewModels/OptimizelyFeatureFlagToolsViewModel.swift
  Library/ViewModels/OptimizelyFeatureFlagToolsViewModelTests.swift
Labels: needs review

#1774 [Unticketed] AWS Secret Key Env Vars Removal From Fastfile
  .fastlane/Fastfile
Labels: enhancement

#1772 [WEB-862] AppTrackingTransparency Authorization
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/AppDelegateViewModelTests.swift
  Kickstarter-iOS/Info.plist
  Kickstarter.xcodeproj/project.pbxproj
  Library/Tracking/ATTrackingAuthorizationStatus.swift
Labels: needs review

#1778 Circleci/pipeline queue
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/AppDelegateViewModelTests.swift
  Kickstarter-iOS/Features/FacebookResetPasswordViewController/Controller/FacebookResetPasswordViewController.swift
  Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift
  Kickstarter-iOS/Features/OptimizelyFeatureFlagTools/Controller/OptimizelyFeatureFlagToolsViewControllerTests.swift
  Kickstarter-iOS/Features/SetYourPassword/Controller/SetYourPasswordViewController.swift
  Kickstarter-iOS/Info.plist
  Kickstarter.xcodeproj/project.pbxproj
  Library/OptimizelyClientTypeTests.swift
  Library/OptimizelyFeature+Helpers.swift
  Library/OptimizelyFeature+HelpersTests.swift
  Library/OptimizelyFeature.swift
  Library/Tracking/ATTrackingAuthorizationStatus.swift
  Library/ViewModels/FacebookResetPasswordViewModel.swift
  Library/ViewModels/FacebookResetPasswordViewModelTests.swift
  Library/ViewModels/OptimizelyFeatureFlagToolsViewModel.swift
  Library/ViewModels/OptimizelyFeatureFlagToolsViewModelTests.swift
  Library/ViewModels/ResetYourFacebookPasswordViewModelTests.swift
  Library/ViewModels/SetYourPasswordViewModel.swift
  Library/ViewModels/SetYourPasswordViewModelTests.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.ResetYourFacebookPasswordViewControllerTests/testSetYourPasswordViewController_DisabledSave_lang_de_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ResetYourFacebookPasswordViewControllerTests/testSetYourPasswordViewController_DisabledSave_lang_de_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ResetYourFacebookPasswordViewControllerTests/testSetYourPasswordViewController_DisabledSave_lang_en_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ResetYourFacebookPasswordViewControllerTests/testSetYourPasswordViewController_DisabledSave_lang_en_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ResetYourFacebookPasswordViewControllerTests/testSetYourPasswordViewController_DisabledSave_lang_es_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ResetYourFacebookPasswordViewControllerTests/testSetYourPasswordViewController_DisabledSave_lang_es_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ResetYourFacebookPasswordViewControllerTests/testSetYourPasswordViewController_DisabledSave_lang_fr_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ResetYourFacebookPasswordViewControllerTests/testSetYourPasswordViewController_DisabledSave_lang_fr_device_phone4_7inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ResetYourFacebookPasswordViewControllerTests/testSetYourPasswordViewController_DisabledSave_lang_ja_device_pad@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.ResetYourFacebookPasswordViewControllerTests/testSetYourPasswordViewController_DisabledSave_lang_ja_device_phone4_7inch@2x.png
Labels: ready to merge

#1775 [PAY-2142] Fix Deeplinks Not Routing From Braze
  Kickstarter-iOS/AppDelegate.swift
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/AppDelegateViewModelTests.swift
  Kickstarter-iOS/Library/BrazeTypes.swift
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KsApi/lib/KsApiNotification.swift
  KsApi/models/BrazePushEnvelope.swift
  Library/Tracking/Segment.swift
Labels: bug, needs review

#1779 [PAY-1527] Local Reward Feature Flag Removed
  Kickstarter-iOS/Features/OptimizelyFeatureFlagTools/Controller/OptimizelyFeatureFlagToolsViewControllerTests.swift
  Kickstarter-iOS/Features/RewardsCollection/Controller/RewardsCollectionViewControllerTests.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/OptimizelyClientTypeTests.swift
  Library/OptimizelyFeature+Helpers.swift
  Library/OptimizelyFeature+HelpersTests.swift
  Library/OptimizelyFeature.swift
  Library/ViewModels/OptimizelyFeatureFlagToolsViewModel.swift
  Library/ViewModels/OptimizelyFeatureFlagToolsViewModelTests.swift
  Library/ViewModels/RewardsCollectionViewModel.swift
  Library/ViewModels/RewardsCollectionViewModelTests.swift
  Screenshots/_64/Kickstarter_Framework_iOSTests.OptimizelyFeatureFlagToolsViewControllerTests/testOptimizelyFeatureFlagToolsViewController@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_FeatureDisabled_RewardNotBacked_NoLocalPickupRewardShown_Success_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_FeatureDisabled_RewardNotBacked_NoLocalPickupRewardShown_Success_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_FeatureDisabled_RewardNotBacked_NoLocalPickupRewardShown_Success_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_FeatureDisabled_RewardNotBacked_NoLocalPickupRewardShown_Success_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_FeatureDisabled_RewardNotBacked_NoLocalPickupRewardShown_Success_lang_ja_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_FeatureEnabled_RewardNotBacked_LocalPickupRewardShown_Success_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_FeatureEnabled_RewardNotBacked_LocalPickupRewardShown_Success_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_FeatureEnabled_RewardNotBacked_LocalPickupRewardShown_Success_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_FeatureEnabled_RewardNotBacked_LocalPickupRewardShown_Success_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_FeatureEnabled_RewardNotBacked_LocalPickupRewardShown_Success_lang_ja_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_RewardBacked_LocalPickupRewardShown_Success_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_RewardBacked_LocalPickupRewardShown_Success_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_RewardBacked_LocalPickupRewardShown_Success_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_RewardBacked_LocalPickupRewardShown_Success_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_RewardBacked_LocalPickupRewardShown_Success_lang_ja_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_RewardNotBacked_AllRewardsShown_Success_lang_de_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_RewardNotBacked_AllRewardsShown_Success_lang_en_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_RewardNotBacked_AllRewardsShown_Success_lang_es_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_RewardNotBacked_AllRewardsShown_Success_lang_fr_device_phone5_8inch@2x.png
  Screenshots/_64/Kickstarter_Framework_iOSTests.RewardsCollectionViewControllerTests/testRewards_LocalPickUp_RewardNotBacked_AllRewardsShown_Success_lang_ja_device_phone5_8inch@2x.png
Labels: enhancement, needs review
