Repository kickstarter/ios-oss, pull requests merged in 2023-02, with the labels that each got.

#1785 [Regression Fix] Braze Segment Integration Crash
  Kickstarter-iOS/AppDelegate.swift
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KsApi/lib/KsApiNotification.swift
Labels: enhancement

#1786 Release 5.6.1 to Main Trigger Beta
  Kickstarter-iOS/AppDelegate.swift
  Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KsApi/lib/KsApiNotification.swift
Labels: ready to merge

#1790 [WEB-958] FIX: FB Deprecation (Set a password) flow disregarding guard statement
  Kickstarter-iOS/Features/LoginTout/Controller/LoginToutViewController.swift
Labels: bug, needs review

#1791 [NTV-647] Braze In-App Notification Fix
  Kickstarter-iOS/AppDelegate.swift
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/AppDelegateViewModelTests.swift
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Library/Tracking/Segment.swift
Labels: needs review

#1793 [Unticketed] Update Segment Appboy Dependency
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: needs review

#1792 [WEB-671]: Setup TriggerCapiEventInput GraphQL Mutation
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/graphql-schema.json
  KsApi/models/graphql/adapters/GraphAPI.TriggerCapiEventInput+TriggerCapiEventInput.swift
  KsApi/models/graphql/adapters/GraphAPI.TriggerCapiEventInput+TriggerCapiEventInputTests.swift
  KsApi/mutations/TriggerCapiEvent.graphql
  KsApi/mutations/inputs/TriggerCapiEventInput.swift
  KsApi/mutations/inputs/TriggerCapiEventInputTests.swift
Labels: needs review

#1795 [WEB-970] Part 1: Add New Property sendMetaCapiEvents
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/fragments/ProjectFragment.graphql
  KsApi/graphql-schema.json
  KsApi/models/Project.swift
  KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
  KsApi/models/graphql/adapters/Project+FetchProjectQueryDataTests.swift
  KsApi/models/graphql/adapters/Project+ProjectFragment.swift
  KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
  KsApi/models/lenses/ProjectLenses.swift
  KsApi/models/templates/ProjectTemplates.swift
  KsApi/mutations/templates/query/FetchAddOnsQueryTemplate.swift
  KsApi/mutations/templates/query/FetchProjectQueryTemplate.swift
Labels: enhancement

#1796 Release 5.6.2 to Main
  Kickstarter.xcodeproj/project.pbxproj
Labels: ready to merge
