Repository kickstarter/ios-oss, pull requests merged in 2023-11, with the labels that each got.

#1877 Increase shallow fetch depth to 100, to make Danger work
  .circleci/config.yml
Labels: bug

#1874 [MBL-1021] Block User Action Sheet
  Kickstarter-iOS/Features/Comments/Controllers/CommentRepliesViewController.swift
  Kickstarter-iOS/Features/Comments/Controllers/CommentsViewController.swift
  Kickstarter-iOS/Features/Comments/Views/Cells/CommentCell.swift
  Kickstarter-iOS/Features/Comments/Views/Cells/RootCommentCell.swift
  Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
  Kickstarter-iOS/Features/Messages/Storyboard/Messages.storyboard
  Kickstarter-iOS/Features/Messages/Views/Cells/MessageCell.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
  Library/UIAlertController.swift
  Library/ViewModels/CommentCellViewModel.swift
  Library/ViewModels/CommentCellViewModelTests.swift
  Library/ViewModels/MessageCellViewModel.swift
  Library/ViewModels/MessageCellViewModelTests.swift
  Library/ViewModels/RootCommentCellViewModel.swift
  Library/ViewModels/RootCommentCellViewModelTests.swift
Labels: enhancement, needs review

#1879 [MBL-1021] Fix user blocking voiceOver
  Kickstarter-iOS/Features/Comments/Views/Cells/CommentCell.swift
  Kickstarter-iOS/Features/Comments/Views/Cells/RootCommentCell.swift
  Kickstarter-iOS/Features/Comments/Views/CommentCellHeaderStackView.swift
  Kickstarter-iOS/Features/Comments/Views/ViewRepliesView.swift
  Kickstarter-iOS/Features/Messages/Views/Cells/MessageCell.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectPamphletMainCell.swift
Labels: enhancement, needs review

#1873 MBL-1014: Replace ReactiveSwift in ReportProjectFormViewModel with Combine
  Kickstarter-iOS/Features/ReportProject/ReportProjectFormView.swift
  Kickstarter-iOS/Features/ReportProject/ReportProjectInfoView.swift
  Kickstarter-iOS/SharedViews/LoadingBarButtonItem.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/combine/CombineTestObserver.swift
  KsApi/combine/Signal+Combine.swift
  KsApi/extensions/ApolloClient+RAC.swift
  KsApi/extensions/MockGraphQLClient.swift
  Library/ViewModels/ReportProjectFormViewModel.swift
  Library/ViewModels/ReportProjectFormViewModelTests.swift
Labels: enhancement

#1881 MBL-1039: Refactor LoadingBarButtonItem to take a closure instead of a binding for save actions
  Kickstarter-iOS/Features/ChangeEmail/Controller/ChangeEmailView.swift
  Kickstarter-iOS/Features/ReportProject/ReportProjectFormView.swift
  Kickstarter-iOS/SharedViews/LoadingBarButtonItem.swift
  Library/ViewModels/ChangeEmailViewModelSwiftUIIntegrationTest.swift
  Library/ViewModels/ReportProjectFormViewModel.swift
Labels: enhancement

#1880 [MBL-1036] Block User Popup + Banner Message
  Kickstarter-iOS/Features/Comments/Controllers/CommentRepliesViewController.swift
  Kickstarter-iOS/Features/Comments/Controllers/CommentsViewController.swift
  Kickstarter-iOS/Features/MessageBanner/Controller/MessageBannerViewController.swift
  Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
  Library/UIAlertController.swift
  Library/ViewModels/CommentRepliesViewModel.swift
  Library/ViewModels/CommentsViewModel.swift
  Library/ViewModels/MessagesViewModel.swift
  Library/ViewModels/ProjectPageViewModel.swift
Labels: enhancement, needs review

#1883 [MBL-1026] Filter comments from blocked users
  Kickstarter-iOS/Features/Comments/Controllers/CommentRepliesViewController.swift
  Kickstarter-iOS/Features/Comments/Controllers/CommentsViewController.swift
  Kickstarter-iOS/Features/Comments/Views/Cells/RootCommentCell.swift
  Kickstarter-iOS/Features/Comments/Views/CommentCellHeaderStackView.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/models/Comment.swift
  KsApi/models/User.swift
  KsApi/models/UserTests.swift
  KsApi/models/templates/CommentTemplates.swift
  Library/ViewModels/CommentCellViewModel.swift
  Library/ViewModels/CommentCellViewModelTests.swift
  Library/ViewModels/RootCommentCellViewModel.swift
  Library/ViewModels/RootCommentCellViewModelTests.swift
Labels: needs review

#1886 Refresh comments when a user is blocked
  Kickstarter-iOS/Features/Comments/Controllers/CommentRepliesViewController.swift
  Kickstarter-iOS/Features/Comments/Controllers/CommentsViewController.swift
Labels: needs review

#1884 [MBL-1037] Use block user translatable strings
  Kickstarter-iOS/Features/Comments/Controllers/CommentRepliesViewController.swift
  Kickstarter-iOS/Features/Comments/Controllers/CommentsViewController.swift
  Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_de_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_en_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_es_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_fr_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_ja_device_pad.png
  Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
  Kickstarter-iOS/Locales/de.lproj/Localizable.strings
  Kickstarter-iOS/Locales/es.lproj/Localizable.strings
  Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
  Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
  Library/Strings.swift
  Library/UIAlertController.swift
  Library/ViewModels/CommentCellViewModel.swift
  Library/ViewModels/ProjectPamphletCreatorHeaderCellViewModelTests.swift
Labels: needs review

#1889 [NO TICKET] Update Block User Strings
  Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
  Kickstarter-iOS/Locales/de.lproj/Localizable.strings
  Kickstarter-iOS/Locales/es.lproj/Localizable.strings
  Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
  Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
  Library/Strings.swift
  Library/UIAlertController.swift
  Library/ViewModels/CommentCellViewModelTests.swift
Labels: enhancement, needs review

#1882 [MBL-957] Add RichPushNotifications push service extension to supportrich push notifications with Braze
  .fastlane/Fastfile
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/xcshareddata/xcschemes/RichPushNotifications.xcscheme
  RichPushNotifications/Info.plist
  RichPushNotifications/NotificationService.swift
Labels: enhancement

#1887 [MBL-1027] Blocked User Messages UI
  Kickstarter-iOS/Features/MessageBanner/Controller/MessageBannerViewController.swift
  Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
  Library/ViewModels/MessagesViewModel.swift
  Library/ViewModels/MessagesViewModelTests.swift
Labels: enhancement, needs review

#1890 MBL-1022: Add blocking mutation to iOS client
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/graphql-schema.json
  KsApi/models/graphql/adapters/GraphAPI.BlockUserInput+BlockUserInput.swift
  KsApi/models/graphql/adapters/GraphAPI.BlockUserInput+BlockUserInputTests.swift
  KsApi/mutations/BlockUser.graphql
  KsApi/mutations/inputs/BlockUserInput.swift
  KsApi/mutations/inputs/BlockUserInputTests.swift
Labels: enhancement

#1891 [MBL-1025] Update User object with server value for isBlocked
  KsApi/GraphAPI.swift
  KsApi/fragments/UserFragment.graphql
  KsApi/models/Comment.swift
  KsApi/models/User.swift
  KsApi/models/UserTests.swift
  KsApi/models/graphql/GraphComment.swift
  KsApi/models/graphql/GraphCommentTests.swift
  KsApi/models/graphql/GraphUser.swift
  KsApi/models/graphql/GraphUserTests.swift
  KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
  KsApi/models/graphql/adapters/Comment+CommentFragment.swift
  KsApi/models/graphql/adapters/Comment+CommentWithRepliesFragment.swift
  KsApi/models/graphql/adapters/Comment+PostCommentMutationData.swift
  KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
  KsApi/models/graphql/adapters/User+UserFragment.swift
  KsApi/models/graphql/adapters/UserCreditCards+UserFragmentTests.swift
  KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelope.swift
  KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelopeTemplates.swift
  KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelopeTests.swift
  KsApi/models/lenses/UserLenses.swift
  KsApi/models/templates/CommentTemplates.swift
  KsApi/models/templates/UserTemplates.swift
  KsApi/models/templates/graphql/GraphUserTemplates.swift
  KsApi/mutations/PostComment.graphql
  KsApi/mutations/PostCommentMutation.swift
  KsApi/mutations/PostCommentMutationTests.swift
  KsApi/mutations/templates/fragment/CommentFragmentTemplate.swift
  KsApi/mutations/templates/fragment/UserFragmentTemplate.swift
  KsApi/mutations/templates/query/FetchProjectFriendsQueryTemplate.swift
  KsApi/mutations/templates/query/FetchProjectQueryTemplate.swift
  KsApi/queries/templates/FetchBackerProjectsQuery.json
  KsApi/queries/templates/FetchBackerProjectsQueryRequestForTests.graphql_test
  Library/ViewModels/MessagesViewModelTests.swift
Labels: needs review
