Repository kickstarter/ios-oss, pull requests merged in 2023-03, with the labels that each got.

#1798 [WEB-970] Add CAPI Events
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/PledgeViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/SharedFunctions.swift
  Library/Tracking/AppTrackingTransparency.swift
  Library/Tracking/FacebookCAPIEventName.swift
  Library/Tracking/KSRAnalytics.swift
  Library/Tracking/KSRAnalyticsTests.swift
  Library/ViewModels/PledgePaymentMethodsViewModel.swift
  Library/ViewModels/PledgePaymentMethodsViewModelTests.swift
  Library/ViewModels/PledgeViewModel.swift
  Library/ViewModels/PledgeViewModelTests.swift
  Library/ViewModels/ProjectPageViewModel.swift
  Library/ViewModels/RewardsCollectionViewModel.swift
  Library/ViewModels/ThanksViewModel.swift
  Library/ViewModels/ThanksViewModelTests.swift
Labels: enhancement

#1801 [WEB-999] Prelaunch Dates Blockers
  Kickstarter-iOS/Features/Dashboard/Controller/DashboardViewControllerTests.swift
  Kickstarter-iOS/Features/DashboardProjects/Views/FundingGraphView.swift
  Kickstarter-iOS/Features/DashboardProjects/Views/FundingGraphViewTests.swift
  Kickstarter-iOS/Library/CookieRefTagFunctions.swift
  KsApi/models/Project.swift
  KsApi/models/lenses/Project.DatesLenses.swift
  KsApi/models/lenses/ProjectLenses.swift
  Library/Tracking/KSRAnalytics.swift
  Library/ViewModels/BackerDashboardProjectCellViewModel.swift
  Library/ViewModels/DashboardFundingCellViewModel.swift
  Library/ViewModels/DashboardFundingCellViewModelTests.swift
  Library/ViewModels/DiscoveryPostcardViewModel.swift
  Library/ViewModels/DiscoveryPostcardViewModelTests.swift
  Library/ViewModels/DiscoveryProjectCardViewModel.swift
  Library/ViewModels/ManagePledgeViewModel.swift
  Library/ViewModels/MostPopularSearchProjectCellViewModel.swift
  Library/ViewModels/PledgeSummaryViewModel.swift
  Library/ViewModels/ProjectActivityLaunchCellViewModel.swift
  Library/ViewModels/ProjectActivitySuccessCellViewModel.swift
  Library/ViewModels/ProjectPamphletCreatorHeaderCellViewModel.swift
  Library/ViewModels/ProjectPamphletMainCellViewModel.swift
  Library/ViewModels/RewardAddOnCardViewModel.swift
  Library/ViewModels/RewardCardViewModel.swift
Labels: needs review

#1799 [WEB-863] Guard Segment Events Behind AppTrackingTransparency
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/AppEnvironment.swift
  Library/Environment.swift
  Library/TestHelpers/MockAppTrackingTransparency.swift
  Library/TestHelpers/TestCase.swift
  Library/TestHelpers/XCTestCase+AppEnvironment.swift
  Library/Tracking/AppTrackingTransparency.swift
  Library/Tracking/KSRAnalytics.swift
  Library/Tracking/KSRAnalyticsTests.swift
  Library/ViewModels/PledgePaymentMethodsViewModel.swift
  Library/ViewModels/PledgeViewModelTests.swift
  Library/ViewModels/ProjectPageViewModel.swift
  Library/ViewModels/RewardsCollectionViewModel.swift
  Library/ViewModels/ThanksViewModel.swift
Labels: enhancement, needs review

#1800 [WEB-1007] FetchUserEmailQuery
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/AppDelegateViewModelTests.swift
  Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/PledgeViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/fragments/UserEmailFragment.graphql
  KsApi/models/UserEnvelope.swift
  KsApi/models/graphql/GraphUserEmail.swift
  KsApi/models/graphql/GraphUserEmailTests.swift
  KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelope.swift
  KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelopeTests.swift
  KsApi/queries/FetchUserEmail.graphql
  Library/AppEnvironment.swift
  Library/Environment.swift
  Library/SharedFunctions.swift
  Library/TestHelpers/MockAppTrackingTransparency.swift
  Library/TestHelpers/TestCase.swift
  Library/TestHelpers/XCTestCase+AppEnvironment.swift
  Library/Tracking/AppTrackingTransparency.swift
  Library/Tracking/KSRAnalytics.swift
  Library/Tracking/KSRAnalyticsTests.swift
  Library/ViewModels/PledgePaymentMethodsViewModel.swift
  Library/ViewModels/PledgePaymentMethodsViewModelTests.swift
  Library/ViewModels/PledgeViewModel.swift
  Library/ViewModels/PledgeViewModelTests.swift
  Library/ViewModels/ProjectPageViewModel.swift
  Library/ViewModels/ProjectPageViewModelTests.swift
  Library/ViewModels/RewardsCollectionViewModel.swift
  Library/ViewModels/ThanksViewModel.swift
  Library/ViewModels/ThanksViewModelTests.swift
Labels: enhancement, needs review

#1805 [MBL-670] Saved Prelaunch Projects on Backer Dashboard -- Merge After MBL-671
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/models/UserEnvelope.swift
  KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelope.swift
  KsApi/models/graphql/adapters/UserEnvelope+GraphUserEnvelopeTests.swift
  Library/ViewModels/BackerDashboardViewModel.swift
  Library/ViewModels/BackerDashboardViewModelTests.swift
Labels: needs review

#1806 Release 5.7.0 to Main
  Kickstarter.xcodeproj/project.pbxproj
Labels: needs review
