Repository kickstarter/ios-oss, pull requests merged in 2023-10, with the labels that each got.

#1863 MBL-988: Add GraphQL query FetchBackerProjectsQuery to replace v1 API calls on backer dashboard
  .circleci/config.yml
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/models/FetchProjectsEnvelope.swift
  KsApi/models/graphql/adapters/FetchProjectsEnvelope+FetchBackerProjectsQueryData.swift
  KsApi/models/graphql/adapters/FetchProjectsEnvelope+FetchBackerProjectsQueryDataTests.swift
  KsApi/queries/FetchBackerProjectsQuery.graphql
  KsApi/queries/templates/FetchBackerProjectsQuery.json
  KsApi/queries/templates/FetchBackerProjectsQueryDataTemplate.swift
  KsApi/queries/templates/FetchBackerProjectsQueryRequestForTests.graphql_test
Labels: bug, needs review

#1865 [MBL-993] Dark Mode Feature Flag
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/RemoteConfigFeatureFlagToolsViewControllerTests.swift
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/__Snapshots__/RemoteConfigFeatureFlagToolsViewControllerTests/testRemoteConfigFeatureFlagToolsViewController.1.png
  Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
  Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift
  Library/RemoteConfig/RemoteConfigFeature.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModelTests.swift
Labels: enhancement

#1867 Store failed snapshots in Failed_Snapshot_Tests/ and save as artifacts
  .circleci/config.yml
  .gitignore
  Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-Framework-iOS.xcscheme
Labels: enhancement

#1870 [MBL-1020] Block Users Feature Flag
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/RemoteConfigFeatureFlagToolsViewControllerTests.swift
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/__Snapshots__/RemoteConfigFeatureFlagToolsViewControllerTests/testRemoteConfigFeatureFlagToolsViewController.1.png
  Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
  Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift
  Library/RemoteConfig/RemoteConfigFeature.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModelTests.swift
Labels: enhancement, needs review

#1872 [MBL-1006] Use shallow clone to speed up build times
  .circleci/config.yml
Labels: enhancement
