Repository kickstarter/ios-oss, pull requests merged in 2023-07, with the labels that each got.

#1830 [MBL-856] Banner For Creator Dashboard Deprecation
  Kickstarter-iOS/Features/Dashboard/Controller/DashboardViewController.swift
  Kickstarter-iOS/Features/DashboardDeprecationBanner/DashboardDeprecationView.swift
  Kickstarter-iOS/Features/RootTabBar/RootTabBarViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
Labels: needs review

#1829 [MBL-866] Remove Add New Card Page
  Kickstarter-iOS/Features/AddNewCard/Controller/AddNewCardViewController.swift
  Kickstarter-iOS/Features/AddNewCard/Controller/AddNewCardViewControllerTests.swift
  Kickstarter-iOS/Features/PaymentMethods/Controller/PaymentMethodsViewController.swift
  Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/ViewModels/AddNewCardViewModel.swift
  Library/ViewModels/AddNewCardViewModelTests.swift
  Library/ViewModels/PaymentMethodsViewModel.swift
  Library/ViewModels/PaymentMethodsViewModelTests.swift
  Library/ViewModels/PledgePaymentMethodsViewModel.swift
  Library/ViewModels/PledgePaymentMethodsViewModelTests.swift
Labels: needs review

#1834 [MBL-864] Stripe Upgrade
  Kickstarter-iOS/Features/AddNewCard/Storyboard/SettingsFormFieldView.xib
  Kickstarter-iOS/Features/AddNewCard/Views/SettingsFormFieldView.swift
  Kickstarter-iOS/Features/PaymentMethods/Controller/PaymentMethodsViewController.swift
  Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
  Kickstarter-iOS/Features/Settings/Storyboard/Settings.storyboard
  Kickstarter-iOS/Features/Settings/Views/PaymentCardTextField.swift
  Kickstarter-iOS/Library/Nib.swift
  Kickstarter-iOS/Library/PaymentSheetPaymentOptionsDisplayData.swift
  Kickstarter-iOS/Library/STPCardBrand+CreditCardType.swift
  Kickstarter-iOS/Library/STPPaymentHandler+StripePaymentHandlerActionStatus.swift
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Library/TestHelpers/Stripe+PaymentMethod.swift
  Library/Tracking/KSRAnalytics.swift
  Library/ViewModels/PaymentMethodsViewModel.swift
  Library/ViewModels/PledgePaymentMethodsViewModel.swift
  Library/ViewModels/PledgePaymentMethodsViewModelTests.swift
Labels: enhancement, needs review

#1835 [MBL 873] Implement TriggerThirdPartyEvent Mutation
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/models/graphql/adapters/GraphAPI.TriggerCapiEventInput+TriggerCapiEventInput.swift
  KsApi/models/graphql/adapters/GraphAPI.TriggerCapiEventInput+TriggerCapiEventInputTests.swift
  KsApi/mutations/TriggerCapiEvent.graphql
  KsApi/mutations/inputs/TriggerCapiEventInput.swift
  KsApi/mutations/inputs/TriggerCapiEventInputTests.swift
  Library/NSBundleType+Tests.swift
  Library/NSBundleType.swift
  Library/TestHelpers/MockBundle.swift
  Library/Tracking/ThirdPartyEventInputName.swift
  Library/ViewModels/PledgePaymentMethodsViewModel.swift
  Library/ViewModels/PledgePaymentMethodsViewModelTests.swift
  Library/ViewModels/ProjectPageViewModel.swift
  Library/ViewModels/RewardsCollectionViewModel.swift
  Library/ViewModels/ThanksViewModel.swift
Labels: enhancement

#1837 [MBL-888] Update Creator Dashboard Deprecation Date
  Kickstarter-iOS/Features/DashboardDeprecationBanner/DashboardDeprecationView.swift
Labels: enhancement
