Repository kickstarter/ios-oss, pull requests merged in 2023-09, with the labels that each got.

#1847 [MBL-958] Ai page polish
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewControllerTests.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_de_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_en_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_es_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_fr_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_ja_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Datasource/Datasource/ProjectPageViewControllerDataSource.swift
  Kickstarter-iOS/Features/ProjectPage/Datasource/Datasource/ProjectPageViewControllerDataSourceTests.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectTabAIGenerationCell.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectTabQuestionAnswerCell.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectTabTitleCell.swift
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/models/ExtendedProjectProperties.swift
  KsApi/models/graphql/adapters/Project+FetchProjectQueryDataTests.swift
  KsApi/models/graphql/adapters/Project+ProjectFragment.swift
  KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
  Library/ViewModels/ProjectTabCategoryDescriptionCellViewModel.swift
  Library/ViewModels/ProjectTabQuestionAnswerCellViewModel.swift
  Library/ViewModels/ProjectTabQuestionAnswerCellViewModelTests.swift
Labels: needs review

#1850 [MBL-960] Fix crash by using default hashing and equality for the config
  Library/Format.swift
  Library/FormatTests.swift
Labels: bug

#1849 [MBL-952] Design System Demo Page (Dark Mode)
  Kickstarter-iOS/Assets.xcassets/colors/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/alert.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/black.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/celebrate100.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/celebrate300.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/celebrate500.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/celebrate700.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/cellSeparator.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/create100.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/create300.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/create500.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/create700.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/facebookBlue.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/inform.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/support100.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/support200.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/support300.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/support400.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/support500.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/support700.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/trust100.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/trust300.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/trust500.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/trust700.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/warn.colorset/Contents.json
  Kickstarter-iOS/Assets.xcassets/colors/white.colorset/Contents.json
  Kickstarter-iOS/Features/BetaTools/Controller/BetaToolsViewController.swift
  Kickstarter-iOS/Features/BetaTools/Controller/__Snapshots__/BetaToolsViewControllerTests/testBetaToolsViewController.1.png
  Kickstarter-iOS/Features/DesignSystem/Colors/DesignSystemColors.swift
  Kickstarter-iOS/Features/DesignSystem/Controller/DesignSystemViewController.swift
  Kickstarter-iOS/Features/DesignSystem/Views/DemoCTAContainerView.swift
  Kickstarter-iOS/Features/DesignSystem/Views/DemoShimmerLoadingView.swift
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Library/ViewModels/BetaToolsViewModel.swift
  Library/ViewModels/BetaToolsViewModelTests.swift
Labels: enhancement, needs review

#1851 [MBL-975] Report This Project Feature Flag
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/RemoteConfigFeatureFlagToolsViewControllerTests.swift
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/__Snapshots__/RemoteConfigFeatureFlagToolsViewControllerTests/testRemoteConfigFeatureFlagToolsViewController.1.png
  Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
  Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift
  Library/RemoteConfig/RemoteConfigFeature.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModelTests.swift
Labels: needs review

#1855 [MBL-982] Support Project Fragment's Flagging Property
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
  KsApi/GraphAPI.swift
  KsApi/models/Project.swift
  KsApi/models/graphql/adapters/Project+FetchProjectQueryData.swift
  KsApi/models/graphql/adapters/Project+FetchProjectQueryDataTests.swift
  KsApi/models/graphql/adapters/Project+ProjectFragment.swift
  KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
  KsApi/models/lenses/ProjectLenses.swift
  KsApi/models/templates/ProjectTemplates.swift
  KsApi/queries/FetchProjectByIdQuery.graphql
  KsApi/queries/FetchProjectBySlugQuery.graphql
  Library/ViewModels/ProjectPageViewModel.swift
  Library/ViewModels/ProjectPageViewModelTests.swift
Labels: needs review

#1858 [MBL-984] Setup CreateFlagging GraphQL Mutation
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/graphql-schema.json
  KsApi/models/graphql/adapters/GraphAPI.CreateFlaggingInput+CreateFlaggingInput.swift
  KsApi/models/graphql/adapters/GraphAPI.CreateFlaggingInput+CreateFlaggingInputTests.swift
  KsApi/mutations/CreateFlagging.graphql
  KsApi/mutations/inputs/CreateFlaggingInput.swift
  KsApi/mutations/inputs/CreateFlaggingInputTests.swift
Labels: needs review

#1857 [MBL-983] Already Reported Project Label
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
  Kickstarter-iOS/Features/ProjectPage/Datasource/Datasource/ProjectPageViewControllerDataSource.swift
  Kickstarter-iOS/Features/ProjectPage/Datasource/Datasource/ProjectPageViewControllerDataSourceTests.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ReportProjectCell.swift
  Kickstarter-iOS/Features/ProjectPage/Views/ReportProjectLabelView.swift
  Kickstarter-iOS/Features/ReportProject/ReportProjectInfoView.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/HelpType.swift
  Library/SwiftUI+Extensions/Text+HTML.swift
  Library/ViewModels/ProjectPageViewModel.swift
  Library/ViewModels/ProjectPageViewModelTests.swift
  Library/ViewModels/ProjectPamphletSubpageCellViewModel.swift
Labels: enhancement, needs review
