Repository kickstarter/ios-oss, pull requests merged in 2023-08, with the labels that each got.

#1836 [MBL-59] Fix personal data export.
  Kickstarter-iOS/Features/SettingsPrivacy/Views/Cells/SettingsPrivacyRequestDataCell.swift
  KsApi/models/ExportDataEnvelope.swift
  KsApi/models/lenses/ExportDataEnvelopeLenses.swift
  Library/ViewModels/SettingsRequestDataCellViewModel.swift
  Library/ViewModels/SettingsRequestDataCellViewModelTests.swift
Labels: bug

#1841 [MBL-897] Feature Flag Use of AI Project Tab
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/__Snapshots__/RemoteConfigFeatureFlagToolsViewControllerTests/testRemoteConfigFeatureFlagToolsViewController.1.png
  KsApi/GraphAPI.swift
  Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
  Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift
  Library/RemoteConfig/RemoteConfigFeature.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModelTests.swift
Labels: needs review

#1839 [MBL-736] Upgrade PerimeterX
  Kickstarter-iOS/AppDelegate.swift
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/AppDelegateViewModelTests.swift
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KsApi/ErrorHandler.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/ServiceTypeTests.swift
  KsApi/extensions/NSURLSession.swift
  KsApi/lib/KsApiNotification.swift
  KsApi/px/MockPerimeterXTypes.swift
  KsApi/px/PerimeterXClient.swift
  KsApi/px/PerimeterXClientTests.swift
  KsApi/px/PerimeterXTypes.swift
Labels: needs review

#1844 [MBL-943] Add Additional Header Support to HTML Parser
  KsApi/lib/HTML Parser/HTMLParserTests.swift
  KsApi/lib/HTML Parser/Templates/HTMLParserTemplates.swift
  KsApi/lib/HTML Parser/View Elements/TextComponent.swift
  KsApi/lib/HTML Parser/View Elements/ViewElementType.swift
  Library/ViewModels/HTML Parser/TextViewElementCellViewModel.swift
  Library/ViewModels/HTML Parser/TextViewElementCellViewModelTests.swift
Labels: needs review

#1845 [ADHOCREQ-106] Redirect to safari for braze links that aren't deep links
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/AppDelegateViewModelTests.swift
Labels: bug

#1843 [MBL-902] [MBL-934] [MBL-928] Use of AI Screen, Analytics, Question Headers, Translations
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewControllerTests.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_de_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_en_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_en_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_es_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_es_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_fr_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_fr_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_ja_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_NonBacker_LiveProjectSwitchedToUseOfAITab_Success.lang_ja_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Datasource/Datasource/ProjectPageViewControllerDataSource.swift
  Kickstarter-iOS/Features/ProjectPage/Datasource/Datasource/ProjectPageViewControllerDataSourceTests.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectTabCategoryDescriptionCell.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectTabCheckmarkListCell.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectTabDisclaimerCell.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectTabQuestionAnswerCell.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectTabTitleCell.swift
  Kickstarter-iOS/Features/ProjectPage/Views/ProjectNavigationSelectorView.swift
  Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
  Kickstarter-iOS/Locales/de.lproj/Localizable.strings
  Kickstarter-iOS/Locales/es.lproj/Localizable.strings
  Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
  Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/models/ExtendedProjectProperties.swift
  KsApi/models/graphql/adapters/Project+FetchProjectQueryDataTests.swift
  KsApi/models/graphql/adapters/Project+ProjectFragment.swift
  KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
  Library/HelpType.swift
  Library/HelpTypeTests.swift
  Library/Strings.swift
  Library/Tracking/KSRAnalytics.swift
  Library/Tracking/KSRAnalyticsTests.swift
  Library/ViewModels/ProjectEnvironmentalCommitmentCellViewModel.swift
  Library/ViewModels/ProjectEnvironmentalCommitmentDisclaimerCellViewModel.swift
  Library/ViewModels/ProjectNavigationSelectorViewModel.swift
  Library/ViewModels/ProjectNavigationSelectorViewModelTests.swift
  Library/ViewModels/ProjectPageViewModel.swift
  Library/ViewModels/ProjectPageViewModelTests.swift
  Library/ViewModels/ProjectTabCategoryDescriptionCellViewModel.swift
  Library/ViewModels/ProjectTabCategoryDescriptionCellViewModelTests.swift
  Library/ViewModels/ProjectTabCheckmarkListCellViewModel.swift
  Library/ViewModels/ProjectTabCheckmarkListCellViewModelTests.swift
  Library/ViewModels/ProjectTabDisclaimerCellViewModel.swift
  Library/ViewModels/ProjectTabDisclaimerCellViewModelTests.swift
  Library/ViewModels/ProjectTabQuestionAnswerCellViewModel.swift
  Library/ViewModels/ProjectTabQuestionAnswerCellViewModelTests.swift
Labels: needs review

#1846 Release 5.10.0 to Main
  Kickstarter.xcodeproj/project.pbxproj
Labels: release
