Repository kickstarter/ios-oss, pull requests merged in 2024-05, with the labels that each got.

#2055 MBL-1374: Handle long add-on names on late pledge confirmation page
  Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PostCampaignPledgeRewardsSummaryViewController.swift
  Kickstarter-iOS/Features/PledgePaymentMethods/Views/Cells/PostCampaignPledgeRewardsSummaryCell.swift
Labels: bug

#2059 [MBL-1439] Remove 'Block Users' Feature Flag
  Kickstarter-iOS/Features/Comments/Controllers/CommentRepliesViewController.swift
  Kickstarter-iOS/Features/Comments/Controllers/CommentsViewController.swift
  Kickstarter-iOS/Features/Comments/Views/Cells/CommentCell.swift
  Kickstarter-iOS/Features/Comments/Views/Cells/RootCommentCell.swift
  Kickstarter-iOS/Features/Messages/Controller/MessagesViewController.swift
  Kickstarter-iOS/Features/Messages/Views/Cells/MessageCell.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/__Snapshots__/RemoteConfigFeatureFlagToolsViewControllerTests/testRemoteConfigFeatureFlagToolsViewController.1.png
  Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
  Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift
  Library/RemoteConfig/RemoteConfigFeature.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModelTests.swift
Labels: tech debt

#2066 [MBL-1431] Fix post button compressing
  Kickstarter-iOS/Features/Comments/Views/CommentInputContainerView.swift
Labels: bug

#2067 [MBL-1515] Update Backing and Reward Fragments With Late Pledge Properties
  KsApi/GraphAPI.swift
  KsApi/fragments/BackingFragment.graphql
  KsApi/fragments/RewardFragment.graphql
  KsApi/models/ActivityTests.swift
  KsApi/models/Backing.swift
  KsApi/models/BackingTests.swift
  KsApi/models/Reward.swift
  KsApi/models/RewardTests.swift
  KsApi/models/graphql/adapters/Backing+BackingFragment.swift
  KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
  KsApi/models/graphql/adapters/Reward+RewardFragment.swift
  KsApi/models/graphql/adapters/Reward+RewardFragmentTests.swift
  KsApi/models/lenses/BackingLenses.swift
  KsApi/models/lenses/RewardLenses.swift
  KsApi/models/templates/BackingTemplates.swift
  KsApi/models/templates/RewardTemplates.swift
  KsApi/mutations/templates/query/FetchAddOnsQueryTemplate.swift
  KsApi/mutations/templates/query/FetchProjectRewardsByIdQueryTemplate.swift
Labels: bug

#2069 Sort backed projects by end date
  KsApi/GraphAPI.swift
  KsApi/models/graphql/adapters/FetchProjectsEnvelope+FetchBackerProjectsQueryData.swift
  KsApi/queries/FetchMyBackedProjectsQuery.graphql
  KsApi/queries/templates/FetchMyBackedProjectsQuery.json
  KsApi/queries/templates/FetchMyBackedProjectsQueryRequestForTests.graphql_test
Labels: bug, post-campaign-pledging

#2071 [MBL-1444] Remove Consent Management Dialog Feature Flag
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/AppDelegateViewModelTests.swift
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/__Snapshots__/RemoteConfigFeatureFlagToolsViewControllerTests/testRemoteConfigFeatureFlagToolsViewController.1.png
  Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
  Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift
  Library/RemoteConfig/RemoteConfigFeature.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModelTests.swift
Labels: tech debt
