Repository kickstarter/ios-oss, pull requests merged in 2024-06, with the labels that each got.

#2082 [MBL-1553] Configure survey webview with url instead of SurveyResponse object
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/Features/Activities/Controller/ActivitiesViewController.swift
  Kickstarter-iOS/Features/SurveyResponse/Controller/SurveyResponseViewController.swift
  Library/Navigation.swift
  Library/NavigationTests.swift
  Library/ViewModels/SurveyResponseViewModel.swift
  Library/ViewModels/SurveyResponseViewModelTests.swift
Labels: bug

#2080 MBL-1456: Stub PPO view and container
  Kickstarter-iOS/Features/PledgedProjectsOverview/PPOContainerViewController.swift
  Kickstarter-iOS/Features/PledgedProjectsOverview/PPOView.swift
  Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModel.swift
  Kickstarter-iOS/Features/PledgedProjectsOverview/PPOViewModelTests.swift
  Kickstarter-iOS/Features/RootTabBar/RootTabBarViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/PagedContainer/PagedContainerViewController.swift
  Library/PagedContainer/PagedContainerViewModel.swift
  Library/ViewModels/RootViewModel.swift
Labels: pledged-projects-overview

#2089 Cleanup Risk Messaging Feature
  Kickstarter-iOS/Features/PledgeView/Controllers/PledgeViewController.swift
  Kickstarter-iOS/Features/RiskMessaging/RiskMessagingViewController.swift
  Kickstarter-iOS/Features/RiskMessaging/RiskMessagingViewControllerTests.swift
  Kickstarter-iOS/Library/SharedFunctionsTests.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/SharedFunctions.swift
  Library/Tracking/KSRAnalytics.swift
  Library/Tracking/KSRAnalyticsTests.swift
  Library/ViewModels/PledgeViewModel.swift
  Library/ViewModels/PledgeViewModelTests.swift
  Library/ViewModels/RiskMessagingViewModel.swift
  Library/ViewModels/RiskMessagingViewModelTests.swift
Labels: tech debt
