Repository kickstarter/ios-oss, pull requests merged in 2024-02, with the labels that each got.

#1924 Clean up RemoteConfigFeature+Helpers and RemoteConfigFeatureFlagToolsViewModel
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/RemoteConfigFeatureFlagToolsViewControllerTests.swift
  Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
  Library/RemoteConfig/RemoteConfigFeature+HelpersTests.swift
  Library/TestHelpers/TestCase.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift
Labels: deletion party

#1926 [MBL-1175] CreateCheckout & CreatePaymentIntent Mutations
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/MockService.swift
  KsApi/Service.swift
  KsApi/ServiceType.swift
  KsApi/graphql-schema.json
  KsApi/models/CreateCheckoutEnvelope.swift
  KsApi/models/CreateCheckoutEnvelopeTests.swift
  KsApi/models/PaymentIntentEnvelope.swift
  KsApi/mutations/CreateCheckout.graphql
  KsApi/mutations/CreateCheckoutMutation.swift
  KsApi/mutations/CreatePaymentIntent.graphql
  KsApi/mutations/CreatePaymentIntentMutation.swift
  KsApi/mutations/inputs/CreateCheckoutInput.swift
  KsApi/mutations/inputs/CreateCheckoutInputTests.swift
  KsApi/mutations/inputs/CreatePaymentIntentInput.swift
  KsApi/mutations/inputs/CreatePaymentIntentInputTests.swift
Labels: enhancement, needs review

#1942 Explicitly add Prelude to Link Libraries phase of Kickstarter-Framework
  Kickstarter.xcodeproj/project.pbxproj
Labels: enhancement

#1927 Update build schema to force you to select correct target when building tests
  Kickstarter.xcodeproj/xcshareddata/xcschemes/Kickstarter-iOS.xcscheme
Labels: enhancement

#1945 Explicitly add Prelude to Link Libraries phase of Library-iOS
  Kickstarter.xcodeproj/project.pbxproj
Labels: enhancement

#1946 Remove old legacyOauthToken code (from 2016)
  Library/AppEnvironment.swift
  Library/AppEnvironmentTests.swift
Labels: deletion party

#1951 [MBL-1207] Pledge Button on Project Page
  Library/RewardCellProjectBackingStateType.swift
  Library/SharedFunctions.swift
  Library/ViewModels/PledgeCTAContainerViewViewModel.swift
  Library/ViewModels/RewardCardContainerViewModel.swift
Labels: post-campaign-pledging

#1952 [MBL-1209] Select Your Reward Title
  Kickstarter-iOS/Features/RewardsCollection/Controller/RewardsCollectionViewController.swift
  Kickstarter-iOS/SharedViews/HeaderFooterViews/RewardsCollectionViewHeaderView.swift
  Kickstarter.xcodeproj/project.pbxproj
Labels: post-campaign-pledging
