Repository kickstarter/ios-oss, pull requests merged in 2025-02, with the labels that each got.

#2278 [MBL-2063] Delete Legacy ConfirmDetails
  Kickstarter-iOS/Features/ConfirmDetails/Controllers/ConfirmDetailsViewController.swift
  Kickstarter-iOS/Features/ConfirmDetails/Views/ConfirmDetailsContinueCTAView.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/NoShippingPledgeViewController.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/NoShippingPostCampaignCheckoutViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/ViewModels/ConfirmDetailsViewModel.swift
  Library/ViewModels/ConfirmDetailsViewModelTests.swift
Labels: tech debt

#2277 [MBL-2063] Delete Legacy RewardAddOnsSelection Classes
  Kickstarter-iOS/Features/ConfirmDetails/Controllers/ConfirmDetailsViewController.swift
  Kickstarter-iOS/Features/ConfirmDetails/Views/ConfirmDetailsContinueCTAView.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/NoShippingPledgeViewController.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/NoShippingPostCampaignCheckoutViewController.swift
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionViewController.swift
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionViewControllerTests.swift
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_EmptyState.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_EmptyState.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_EmptyState.lang_es_device_phone5_5inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_EmptyState.lang_fr_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_EmptyState.lang_ja_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Error.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Error.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Error.lang_es_device_phone5_5inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Error.lang_fr_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Error.lang_ja_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShipping.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShipping.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShipping.lang_es_device_phone5_5inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShipping.lang_fr_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShipping.lang_ja_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShippingWithLocalPickup_Success.lang_de_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShippingWithLocalPickup_Success.lang_en_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShippingWithLocalPickup_Success.lang_es_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShippingWithLocalPickup_Success.lang_fr_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShippingWithLocalPickup_Success.lang_ja_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Shipping.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Shipping.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Shipping.lang_es_device_phone5_5inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Shipping.lang_fr_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Shipping.lang_ja_device_pad.png
  Kickstarter.xcodeproj/project.pbxproj
  Library/ViewModels/ConfirmDetailsViewModel.swift
  Library/ViewModels/ConfirmDetailsViewModelTests.swift
  Library/ViewModels/RewardAddOnSelectionNoShippingViewModel.swift
  Library/ViewModels/RewardAddOnSelectionViewModel.swift
  Library/ViewModels/RewardAddOnSelectionViewModelTests.swift
Labels: tech debt

#2280 [MBL-2102] Ineligible badge showing USD instead of EUR for EUR-based projects
  KsApi/models/graphql/adapters/Project+ProjectFragment.swift
Labels: Pledge Over Time

#2286 [MBL-2072] Adds PPO V2 Feature Flag
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/__Snapshots__/RemoteConfigFeatureFlagToolsViewControllerTests/testRemoteConfigFeatureFlagToolsViewController.1.png
  Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
  Library/RemoteConfig/RemoteConfigFeature.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift
Labels: pledged-projects-overview-v2

#2285 Rename NoShippingPostCampaign To PostCampaign
  Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewControllerTests.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_AddOns_LoggedOut.lang_de_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_AddOns_LoggedOut.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_AddOns_LoggedOut.lang_es_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_AddOns_LoggedOut.lang_fr_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_AddOns_LoggedOut.lang_ja_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_es_device_phone5_5inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_fr_device_phone5_8inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_ja_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_ShowsEstimatedShippingView.lang_de_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_ShowsEstimatedShippingView.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_ShowsEstimatedShippingView.lang_es_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_ShowsEstimatedShippingView.lang_fr_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_ShowsEstimatedShippingView.lang_ja_device_phone4_7inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionNoShippingViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/ViewModels/PostCampaignCheckoutViewModel.swift
  Library/ViewModels/PostCampaignCheckoutViewModelTests.swift
Labels: tech debt

#2275 [MBL-1975] Project notice
  Kickstarter-iOS/Features/PledgedProjectsOverview/PPOStyles.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewControllerTests.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/RestrictedCreatorViewController.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/RestrictedCreatorViewControllerTests.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedIn_Backer_LiveProject_NonUS_ProjectCurrency_US_ProjectCountry_NonUS_UserChosenCurrency_NotOmittingCurrencyCode_Success.lang_de_device_phone5_8inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedIn_Backer_LiveProject_NonUS_ProjectCurrency_US_ProjectCountry_NonUS_UserChosenCurrency_NotOmittingCurrencyCode_Success.lang_es_device_phone5_8inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedIn_Backer_LiveProject_NonUS_ProjectCurrency_US_ProjectCountry_NonUS_UserChosenCurrency_NotOmittingCurrencyCode_Success.lang_ja_device_phone5_8inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedIn_Backer_LiveProject_US_ProjectCurrency_US_ProjectCountry_US_UserChosenCurrency_OmittingCurrencyCode_Success.lang_de_device_phone5_8inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedIn_Backer_LiveProject_US_ProjectCurrency_US_ProjectCountry_US_UserChosenCurrency_OmittingCurrencyCode_Success.lang_es_device_phone5_8inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedIn_Backer_LiveProject_US_ProjectCurrency_US_ProjectCountry_US_UserChosenCurrency_OmittingCurrencyCode_Success.lang_ja_device_phone5_8inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_LiveProject_ShowProjectNotice.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_LiveProject_ShowProjectNotice.lang_en_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_LiveProject_ShowProjectNotice.lang_es_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_LiveProject_ShowProjectNotice.lang_fr_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/ProjectPageViewControllerTests/testLoggedOut_LiveProject_ShowProjectNotice.lang_ja_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/RestrictedCreatorViewControllerTests/testView.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/RestrictedCreatorViewControllerTests/testView.lang_en_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/RestrictedCreatorViewControllerTests/testView.lang_es_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/RestrictedCreatorViewControllerTests/testView.lang_fr_device_pad.png
  Kickstarter-iOS/Features/ProjectPage/Controller/__Snapshots__/RestrictedCreatorViewControllerTests/testView.lang_ja_device_phone4inch.png
  Kickstarter-iOS/Features/ProjectPage/Datasource/Datasource/ProjectPageViewControllerDataSourceTests.swift
  Kickstarter-iOS/Features/ProjectPage/Views/Cells/ProjectPamphletMainCell.swift
  Kickstarter-iOS/Locales/Base.lproj/Localizable.strings
  Kickstarter-iOS/Locales/de.lproj/Localizable.strings
  Kickstarter-iOS/Locales/es.lproj/Localizable.strings
  Kickstarter-iOS/Locales/fr.lproj/Localizable.strings
  Kickstarter-iOS/Locales/ja.lproj/Localizable.strings
  Kickstarter-iOS/SharedViews/AlertBanner.swift
  Kickstarter-iOS/SharedViews/AlertBannerTests.swift
  Kickstarter-iOS/SharedViews/__Snapshots__/AlertBannerTests/testView.1.png
  Kickstarter.xcodeproj/project.pbxproj
  KsApi/GraphAPI.swift
  KsApi/fragments/ProjectFragment.graphql
  KsApi/graphql-schema.json
  KsApi/models/ExtendedProjectProperties.swift
  KsApi/models/graphql/adapters/Backing+BackingFragmentTests.swift
  KsApi/models/graphql/adapters/Project+ProjectFragment.swift
  KsApi/models/graphql/adapters/Project+ProjectFragmentTests.swift
  KsApi/models/lenses/ProjectLenses.swift
  KsApi/mutations/templates/query/FetchAddOnsQueryTemplate.swift
  KsApi/mutations/templates/query/FetchProjectQueryTemplate.swift
  KsApi/queries/templates/FetchMyBackedProjectsQuery.json
  KsApi/queries/templates/FetchMySavedProjectsQuery.json
  Library/Strings.swift
  Library/Styles/Colors.swift
  Library/ViewModels/ProjectNavigationSelectorViewModelTests.swift
  Library/ViewModels/ProjectPageViewModel.swift
  Library/ViewModels/ProjectPageViewModelTests.swift
  Library/ViewModels/ProjectPamphletMainCellViewModel.swift
Labels: user trust

#2284 [MBL-2105] Rename NoShippingPledgeViewController & NoShippingPledgeViewModel
  Kickstarter-iOS/Features/ManagePledge/Controllers/ManagePledgeViewController.swift
  Kickstarter-iOS/Features/PledgePaymentMethods/Controller/PledgePaymentMethodsViewController.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/PledgeViewController.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/PledgeViewControllerTests.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewController.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/PostCampaignCheckoutViewControllerTests.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_HasAddOns.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_HasAddOns.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_PledgeContext_FixPaymentMethod_ErroredCard.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_es_device_phone5_5inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_fr_device_phone5_8inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_ja_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_PledgeWithNoReward.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_PledgeWithNoReward.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowCollectionPlans_Ineligible.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowCollectionPlans_Ineligible.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowCollectionPlans_PledgeInFull.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowCollectionPlans_PledgeInFull.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowCollectionPlans_PledgeOverTime.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowCollectionPlans_PledgeOverTime.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowsEstimatedShippingView.lang_de_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowsEstimatedShippingView.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowsEstimatedShippingView.lang_es_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowsEstimatedShippingView.lang_fr_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowsEstimatedShippingView.lang_ja_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowsShippingSummaryViewSection.lang_de_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowsShippingSummaryViewSection.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowsShippingSummaryViewSection.lang_es_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowsShippingSummaryViewSection.lang_fr_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PledgeViewControllerTests/testView_ShowsShippingSummaryViewSection.lang_ja_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_AddOns_LoggedOut.lang_de_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_AddOns_LoggedOut.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_AddOns_LoggedOut.lang_es_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_AddOns_LoggedOut.lang_fr_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_AddOns_LoggedOut.lang_ja_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_es_device_phone5_5inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_fr_device_phone5_8inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_PledgeContext_UnavailableStoredCards.lang_ja_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_ShowsEstimatedShippingView.lang_de_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_ShowsEstimatedShippingView.lang_en_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_ShowsEstimatedShippingView.lang_es_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_ShowsEstimatedShippingView.lang_fr_device_pad.png
  Kickstarter-iOS/Features/PledgeView/Controllers/__Snapshots__/PostCampaignCheckoutViewControllerTests/testView_ShowsEstimatedShippingView.lang_ja_device_phone4_7inch.png
  Kickstarter-iOS/Features/PledgeView/Views/NoShippingPledgeViewCTAContainerView.swift
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionNoShippingViewController.swift
  Kickstarter-iOS/Features/RewardsCollection/Controller/WithShippingRewardsCollectionViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/ViewModels/PledgeViewCTAContainerViewModel.swift
  Library/ViewModels/PledgeViewCTAContainerViewModelTests.swift
  Library/ViewModels/PledgeViewModel.swift
  Library/ViewModels/PledgeViewModelTests.swift
  Library/ViewModels/PostCampaignCheckoutViewModel.swift
  Library/ViewModels/PostCampaignCheckoutViewModelTests.swift
Labels: tech debt

#2295 Rename RewardAddOnNoShippingSelectionViewController, NoShippingPledgeRewardsSummaryDataSource, and WithShippingRewardsCollectionViewController
  Kickstarter-iOS/Features/ManagePledge/Controllers/ManagePledgeViewController.swift
  Kickstarter-iOS/Features/PledgePaymentMethods/Datasource/NoShippingPledgeRewardsSummaryDataSource.swift
  Kickstarter-iOS/Features/ProjectPage/Controller/ProjectPageViewController.swift
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionViewController.swift
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionViewControllerTests.swift
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView.lang_es_device_phone5_5inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView.lang_fr_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView.lang_ja_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_EmptyState.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_EmptyState.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_EmptyState.lang_es_device_phone5_5inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_EmptyState.lang_fr_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_EmptyState.lang_ja_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Error.lang_de_device_phone4inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Error.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Error.lang_es_device_phone5_5inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Error.lang_fr_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_Error.lang_ja_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShippingWithLocalPickup_Success.lang_de_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShippingWithLocalPickup_Success.lang_en_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShippingWithLocalPickup_Success.lang_es_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShippingWithLocalPickup_Success.lang_fr_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_NoShippingWithLocalPickup_Success.lang_ja_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_noAddOns.lang_de_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_noAddOns.lang_en_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_noAddOns.lang_es_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_noAddOns.lang_fr_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_noAddOns.lang_ja_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_noReward.lang_de_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_noReward.lang_en_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_noReward.lang_es_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_noReward.lang_fr_device_pad.png
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/__Snapshots__/RewardAddOnSelectionViewControllerTests/testView_noReward.lang_ja_device_phone5_8inch.png
  Kickstarter-iOS/Features/RewardsCollection/Controller/RewardsCollectionViewController.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/ViewModels/RewardAddOnSelectionViewModel.swift
  Library/ViewModels/RewardAddOnSelectionViewModelTests.swift
Labels: tech debt

#2299 [MBL-2105] Rename WithShippingRewardsCollectionViewHeaderView, WithShippingRewardsCollectionViewController, WithShippingRewardsCollectionViewController & WithShippingRewardsCollectionViewModel
  Kickstarter-iOS/Features/ManagePledge/Controllers/ManagePledgeViewController.swift
  Kickstarter-iOS/Features/PledgePaymentMethods/Datasource/PledgeRewardsSummaryDiffableDataSource.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/PledgeViewController.swift
  Kickstarter-iOS/Features/PledgeView/Controllers/PledgeViewControllerTests.swift
  Kickstarter-iOS/Features/RewardAddOnSelection/Controller/RewardAddOnSelectionViewControllerTests.swift
  Kickstarter-iOS/Features/RewardsCollection/Controller/RewardsCollectionViewController.swift
  Kickstarter-iOS/SharedViews/HeaderFooterViews/RewardsCollectionViewHeaderView.swift
  Kickstarter-iOS/SharedViews/HeaderFooterViews/RewardsWithShippingCollectionViewHeaderView.swift
  Kickstarter.xcodeproj/project.pbxproj
  Library/ViewModels/ManagePledgeViewModel.swift
  Library/ViewModels/ManagePledgeViewModelTests.swift
  Library/ViewModels/PledgeViewModel.swift
  Library/ViewModels/PledgeViewModelTests.swift
  Library/ViewModels/PostCampaignCheckoutViewModelTests.swift
  Library/ViewModels/RewardAddOnSelectionViewModelTests.swift
  Library/ViewModels/RewardsCollectionViewModel.swift
Labels: tech debt

#2304 [MBL-2079] Replace Send Message Text and Icon On PPOProjectCard
  Kickstarter-iOS/Assets.xcassets/icons/icon-send-message.imageset/Contents.json
  Kickstarter-iOS/Assets.xcassets/icons/icon-send-message.imageset/Message.pdf
  Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCardModel+Templates.swift
  Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/PPOProjectCreator.swift
  Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/__Snapshots__/PPOProjectCardTests/testAddressLocks.addressLocks.png
  Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/__Snapshots__/PPOProjectCardTests/testCardAuthPledgeDropped.cardAuthPledgeDropped.png
  Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/__Snapshots__/PPOProjectCardTests/testPaymentFailedPledgeDropped.paymentFailedPledgeDropped.png
  Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/__Snapshots__/PPOProjectCardTests/testShortTemplateText.testShortTemplateText.png
  Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/__Snapshots__/PPOProjectCardTests/testSurveyAvailable.surveyAvailable.png
  Kickstarter-iOS/Features/PledgedProjectsOverview/CardView/__Snapshots__/PPOProjectCardTests/testSurveyAvailableAddressLocks.surveyAvailableAddressLocks.png
  Kickstarter-iOS/Features/PledgedProjectsOverview/PPOStyles.swift
Labels: pledged-projects-overview-v2
