Repository kickstarter/ios-oss, pull requests merged in 2025-05, with the labels that each got.

#2419 [MBL-2418] Lottie SDK Integration
  Kickstarter.xcodeproj/project.pbxproj
  Kickstarter.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: onboarding-flow

#2420 [MBL-2416] Onboarding Flow Feature Flag
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/__Snapshots__/RemoteConfigFeatureFlagToolsViewControllerTests/testRemoteConfigFeatureFlagToolsViewController.1.png
  Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
  Library/RemoteConfig/RemoteConfigFeature.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift
Labels: onboarding-flow

#2433 [Part 1]: Add LegacyColor type, with values for all legacy design system colors
  Kickstarter-iOS/Features/DesignSystem/Controller/ColorsView.swift
  Kickstarter-iOS/Features/DesignSystem/Controller/ColorsViewTests.swift
  Kickstarter-iOS/Features/DesignSystem/Controller/__Snapshots__/ColorsViewTests/testView.colorsView_testView.png
  Kickstarter.xcodeproj/project.pbxproj
  Library/AppEnvironment.swift
  Library/ColorResolver.swift
  Library/Environment.swift
  Library/Styles/Colors/CoreColor.swift
  Library/Styles/Colors/LegacyColors.swift
  Library/Styles/Colors/NewDesignSystemColors.swift
  Library/Styles/Colors/SemanticColor.swift
  Library/TestHelpers/TestCase.swift
  Library/TestHelpers/XCTestCase+AppEnvironment.swift
Labels: dark-mode

#2437 [Part 4] Enable dark mode when featureDarkModeEnabled() is true
  Kickstarter-iOS/AppDelegate.swift
  Kickstarter-iOS/AppDelegateViewModel.swift
  Kickstarter-iOS/AppDelegateViewModelTests.swift
  Kickstarter-iOS/Info.plist
Labels: dark-mode

#2438 Remove feature flag for Phase 2 search filters
  Kickstarter-iOS/Features/RemoteConfigFeatureFlagTools/Controller/__Snapshots__/RemoteConfigFeatureFlagToolsViewControllerTests/testRemoteConfigFeatureFlagToolsViewController.1.png
  Kickstarter-iOS/Features/Search/Controller/SearchViewController.swift
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_PrelaunchProject_InSearch_Success.lang_de_device_phone5_8inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_PrelaunchProject_InSearch_Success.lang_en_device_pad.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_PrelaunchProject_InSearch_Success.lang_es_device_phone5_8inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_PrelaunchProject_InSearch_Success.lang_fr_device_pad.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_PrelaunchProject_InSearch_Success.lang_ja_device_phone5_8inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_SearchState.lang_de_device_phone4_7inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_SearchState.lang_en_device_phone5_8inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_SearchState.lang_es_device_pad.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_SearchState.lang_fr_device_phone4_7inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_SearchState.lang_ja_device_phone5_8inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_defaultState.lang_de_device_phone4_7inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_defaultState.lang_en_device_phone5_8inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_defaultState.lang_es_device_pad.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_defaultState.lang_fr_device_phone4_7inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_defaultState.lang_ja_device_phone5_8inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_loadingMoreResults.lang_en_device_pad.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_loadingMoreResults.lang_en_device_phone4_7inch.png
  Kickstarter-iOS/Features/Search/Controller/__Snapshots__/SearchViewControllerTests/testView_loadingMoreResults.lang_en_device_phone5_8inch.png
  Kickstarter-iOS/Features/Search/Extensions/Category+FilterCategory.swift
  Kickstarter-iOS/Features/SortFilter/FilterCategory/FilterCategoryView.swift
  Kickstarter-iOS/Features/SortFilter/FilterCategory/FilterCategoryViewModelTest_PhaseOne.swift
  Kickstarter-iOS/Features/SortFilter/FilterCategory/FilterCategoryViewModel_PhaseOne.swift
  Kickstarter-iOS/Features/SortFilter/FilterCategory/FilterCategoryViewTest_PhaseOne.swift
  Kickstarter-iOS/Features/SortFilter/FilterCategory/FilterCategoryView_PhaseOne.swift
  Kickstarter-iOS/Features/SortFilter/FilterCategory/__Snapshots__/FilterCategoryViewTest_PhaseOne/testFilterCategoryView_CategoriesList.1.png
  Kickstarter-iOS/Features/SortFilter/FilterCategory/__Snapshots__/FilterCategoryViewTest_PhaseOne/testFilterCategoryView_LoadingState.1.png
  Kickstarter.xcodeproj/project.pbxproj
  Library/RemoteConfig/RemoteConfigFeature+Helpers.swift
  Library/RemoteConfig/RemoteConfigFeature.swift
  Library/UseCases/SearchFilters/SelectedSearchFilters.swift
  Library/ViewModels/RemoteConfigFeatureFlagToolsViewModel.swift
Labels: sort-and-filter

#2445 Update Activity feed for dark mode
  Kickstarter-iOS/Features/Activities/Storyboard/Activity.storyboard
  Kickstarter-iOS/Features/Activities/Views/Cells/ActivityFriendBackingCell.swift
  Kickstarter-iOS/Features/Activities/Views/Cells/ActivityFriendFollowCell.swift
  Kickstarter-iOS/Features/Activities/Views/Cells/ActivityProjectStatusCell.swift
  Kickstarter-iOS/Features/Activities/Views/Cells/ActivitySurveyResponseCell.swift
  Kickstarter-iOS/Features/Activities/Views/Cells/ActivityUpdateCell.swift
  Kickstarter-iOS/Features/Activities/Views/Cells/FindFriendsFacebookConnectCell.swift
  Kickstarter-iOS/Features/Discovery/Storyboard/DiscoveryPage.storyboard
  Kickstarter-iOS/Features/Discovery/Views/Cells/ActivitySampleBackingCell.swift
  Kickstarter-iOS/Features/Discovery/Views/Cells/ActivitySampleFollowCell.swift
  Kickstarter-iOS/Features/Discovery/Views/Cells/ActivitySampleProjectCell.swift
Labels: dark-mode
