Repository kickstarter/ios-oss, pull requests merged in 2025-08, with the labels that each got.

#2576 MBL-2644: Use translated strings for refunded PLOT payments
  Kickstarter-iOS/Features/ManagePledge/Controllers/__Snapshots__/ManagePledgeViewControllerTests/testView_CurrentUser_IsBacker_PledgeOverTime_PaymentSchedule_Expanded.lang_de_device_phone4_7inch.png
  Kickstarter-iOS/Features/ManagePledge/Controllers/__Snapshots__/ManagePledgeViewControllerTests/testView_CurrentUser_IsBacker_PledgeOverTime_PaymentSchedule_Expanded.lang_en_device_pad.png
  Kickstarter-iOS/Features/ManagePledge/Controllers/__Snapshots__/ManagePledgeViewControllerTests/testView_CurrentUser_IsBacker_PledgeOverTime_PaymentSchedule_Expanded.lang_es_device_phone4_7inch.png
  Kickstarter-iOS/Features/ManagePledge/Controllers/__Snapshots__/ManagePledgeViewControllerTests/testView_CurrentUser_IsBacker_PledgeOverTime_PaymentSchedule_Expanded.lang_fr_device_pad.png
  Kickstarter-iOS/Features/ManagePledge/Controllers/__Snapshots__/ManagePledgeViewControllerTests/testView_CurrentUser_IsBacker_PledgeOverTime_PaymentSchedule_Expanded.lang_ja_device_phone4_7inch.png
  Kickstarter-iOS/Features/ManagePledge/Controllers/__Snapshots__/PledgeOverTimePaymentScheduleViewControllerTest/testView_PaymentSchedule_Expanded.lang_en_device_pad_style_light.png
  Kickstarter-iOS/Features/ManagePledge/Controllers/__Snapshots__/PledgeOverTimePaymentScheduleViewControllerTest/testView_PaymentSchedule_Expanded.lang_en_device_phone4_7inch_style_dark.png
  Library/ViewModels/PledgePaymentIncrementState+Extension.swift
Labels: Pledge Over Time

#2579 Onboarding Colors Should Be Static
  Kickstarter-iOS/AppDelegate.swift
Labels: onboarding-flow

#2572 MBL-2653: Add spacing constants to design system
  Kickstarter.xcodeproj/project.pbxproj
  Library/Styles/Spacing/CoreSpacing.swift
  Library/Styles/Spacing/Dimension.swift
Labels: design-system
